import type { ContractYaml } from '../contract/index.js';
import { CliError } from '../../cli/errors.js';
import { SUMMON_AUDIT_EVENTS } from './audit-events.js';
import type { SummonStateStore } from './summon-state-store.js';
import type { AuditLog } from '../../foundation/audit/index.js';
import type { TaskId } from '../async-task-system/types.js';

export interface SummonContractCreateGate {
  /**
   * Gate check before CLI accepts contract create.
   *
   * Behavior matrix:
   * - subagentTaskId 未设 → no-op pass（非子代理路径，如用户手动 CLI）
   * - subagentTaskId 已设 + store 找不到 decision → audit warn + pass（非 summon 子代理路径，如 spawn）
   * - subagentTaskId 已设 + decision.verify=true → pass
   * - subagentTaskId 已设 + decision.verify=false + contract.verification 空/缺 → pass
   * - subagentTaskId 已设 + decision.verify=false + contract.verification 非空 → throw CliError + audit
   */
  check(subagentTaskId: string | undefined, contract: ContractYaml): Promise<void>;
}

export function createSummonContractCreateGate(
  store: SummonStateStore,
  audit?: AuditLog,
): SummonContractCreateGate {
  return {
    async check(subagentTaskId, contract) {
      if (!subagentTaskId) return;

      const decision = await store.read(subagentTaskId as TaskId);
      if (!decision) {
        audit?.write(
          SUMMON_AUDIT_EVENTS.SUMMON_GATE_NO_DECISION,
          `subagentTaskId=${subagentTaskId}`,
          'reason=likely_non_summon_subagent',
        );
        return;
      }

      if (decision.verify) return;

      const hasVerification = Array.isArray(contract.verification) && contract.verification.length > 0;
      if (!hasVerification) return;

      audit?.write(
        SUMMON_AUDIT_EVENTS.SUMMON_VERIFY_FALSE_VIOLATION,
        `subagentTaskId=${subagentTaskId}`,
        `targetClaw=${decision.targetClaw ?? '(unset)'}`,
        `verificationCount=${contract.verification!.length}`,
      );

      throw new CliError(
        `SUMMON_VERIFY_FALSE_VIOLATION: this contract was generated by a summon subagent ` +
        `dispatched with verify=false (default), but contract.yaml contains a non-empty ` +
        `verification array (${contract.verification!.length} entries). Either:\n` +
        `  - Remove the verification array from contract.yaml (recommended; matches summon default), or\n` +
        `  - Caller re-dispatches summon with explicit verify=true if verification is actually required.`,
      );
    },
  };
}
