/**
 * Tool profiles - define which tools are available in each profile
 */

import type { ToolProfile } from '../../types/config.js';
import {
  READ_TOOL_NAME,
  WRITE_TOOL_NAME,
  SEARCH_TOOL_NAME,
  LS_TOOL_NAME,
  SEND_TOOL_NAME,
  DONE_TOOL_NAME,
  SKILL_TOOL_NAME,
  EXEC_TOOL_NAME,
  STATUS_TOOL_NAME,
  MEMORY_SEARCH_TOOL_NAME,
  SPAWN_TOOL_NAME,
  ASK_MOTION_TOOL_NAME,
  DISPATCH_TOOL_NAME,
} from './tool-names.js';

export type ToolName =
  | typeof READ_TOOL_NAME
  | typeof WRITE_TOOL_NAME
  | typeof SEARCH_TOOL_NAME
  | typeof LS_TOOL_NAME
  | typeof SEND_TOOL_NAME
  | typeof DONE_TOOL_NAME
  | typeof SKILL_TOOL_NAME
  | typeof EXEC_TOOL_NAME
  | typeof STATUS_TOOL_NAME
  | typeof MEMORY_SEARCH_TOOL_NAME
  | typeof SPAWN_TOOL_NAME
  | typeof ASK_MOTION_TOOL_NAME
  | typeof DISPATCH_TOOL_NAME;

/**
 * Tool name lists for each profile
 */
export const TOOL_PROFILES: Record<ToolProfile, ToolName[]> = {
  full:     [READ_TOOL_NAME, WRITE_TOOL_NAME, SEARCH_TOOL_NAME, LS_TOOL_NAME, SEND_TOOL_NAME, DONE_TOOL_NAME, SPAWN_TOOL_NAME, DISPATCH_TOOL_NAME, SKILL_TOOL_NAME, EXEC_TOOL_NAME, STATUS_TOOL_NAME, MEMORY_SEARCH_TOOL_NAME],
  readonly: [READ_TOOL_NAME, SEARCH_TOOL_NAME, LS_TOOL_NAME, STATUS_TOOL_NAME, MEMORY_SEARCH_TOOL_NAME],
  subagent: [READ_TOOL_NAME, WRITE_TOOL_NAME, SEARCH_TOOL_NAME, LS_TOOL_NAME, EXEC_TOOL_NAME, SKILL_TOOL_NAME, MEMORY_SEARCH_TOOL_NAME],
  miner:    [READ_TOOL_NAME, WRITE_TOOL_NAME, SEARCH_TOOL_NAME, LS_TOOL_NAME, EXEC_TOOL_NAME, SKILL_TOOL_NAME, MEMORY_SEARCH_TOOL_NAME, ASK_MOTION_TOOL_NAME],
  dream:    [READ_TOOL_NAME, SEARCH_TOOL_NAME, LS_TOOL_NAME, MEMORY_SEARCH_TOOL_NAME],
  verifier: [READ_TOOL_NAME, LS_TOOL_NAME, SEARCH_TOOL_NAME, EXEC_TOOL_NAME],
};
