// Auto-generated by Phase 1008 Step C: merged arch invariant tests.
// Do not edit manually; edit the original per-topic tests instead.

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import config from '../../../.config/dependency-cruiser.cjs';

describe('depcruise-config-allowlist-invariant', () => {

// @ts-ignore — CJS config loaded in ESM test context


/**
 * dependency-cruiser config allowlist sync with design row (phase 1298)
 *
 * 反向：防 dep-cruise config silent 改 allowlist 漏 sync design row
 * (mirror phase 1283 vitest grep test 模式扩到 config sync 维度)
 *
 * 若 future 加新 bootstrap site / 新 design intent file → 必同时更新:
 *   1. 本 test allowlist 期望
 *   2. design row §3.1 (l1_filesystem.md「Bootstrap 与 design intent allowlist」) 列表
 *   3. .dependency-cruiser.cjs 配置
 */
describe('dependency-cruiser config: allowlist sync (phase 1298 / phase 572 extended)', () => {
  it('fs-only-via-foundation-filesystem allowlist matches 4 design intent file', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'fs-only-via-foundation-filesystem',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.pathNot).toEqual([
      '^src/foundation/fs/',
      '^src/foundation/audit/writer\\.ts$',
      '^src/foundation/audit/reader\\.ts$',
      '^src/foundation/process-exec/spawn-detached\\.ts$',
    ]);
  });

  it('nodefilesystem-only-from-bootstrap allowlist matches 6 bootstrap site + fs impl', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'nodefilesystem-only-from-bootstrap',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.pathNot).toEqual([
      '^src/assembly/assemble\\.ts$',
      '^src/assembly/core-infrastructure\\.ts$',
      '^src/cli/index\\.ts$',
      '^src/daemon-entry\\.ts$',
      '^src/daemon-handlers\\.ts$',
      '^src/watchdog-entry\\.ts$',
      '^src/foundation/fs/',
    ]);
  });

  // phase 572 扩: 加 3 sister rule (crypto/child_process/net) allowlist sync invariant
  // 同型 phase 455/490/491 立 (sister to fs-only / nodefilesystem-only pattern)

  it('crypto-only-from-foundation allowlist matches 2 owner module (node-utils/crypto + node-utils/id)', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'crypto-only-from-foundation',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.pathNot).toEqual([
      '^src/foundation/node-utils/crypto\\.ts$',
      '^src/foundation/node-utils/id\\.ts$',
    ]);
  });

  it('child-process-only-from-foundation-process-exec allowlist matches foundation/process-exec/ dir', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'child-process-only-from-foundation-process-exec',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.pathNot).toEqual([
      '^src/foundation/process-exec/',
    ]);
  });

  it('net-only-from-foundation-transport allowlist matches foundation/transport/ dir', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'net-only-from-foundation-transport',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.pathNot).toEqual([
      '^src/foundation/transport/',
    ]);
  });
});
});

describe('depcruise-no-circular-rule', () => {

describe('dependency-cruiser: no-circular rule (phase 1316 终升 error / cleanup roadmap 5/5 完成)', () => {
  it('no-circular rule present at error severity (phase 1316 终升 / 0 cycle 不容回归)', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'no-circular',
    );
    expect(rule).toBeDefined();
    // phase 1316 终升: severity 'error' (cleanup roadmap 5/5 完成 / 0 cycle / future drift fail-loud)
    expect(rule.severity).toBe('error');
    expect(rule.to.circular).toBe(true);
  });
});
});

describe('depcruise-options-baseline-invariant', () => {

/**
 * phase 615: invariant that .config/dependency-cruiser.cjs options has the
 * baseline configuration:
 * - options.tsConfig.fileName === 'tsconfig.json'
 * - options.doNotFollow.path === 'node_modules'
 * - options.exclude.path === '^(tests|scripts|dist|node_modules)'
 *
 * Rationale:
 * - tsConfig.fileName drift → depcruise loses path-alias resolution → all
 *   TS path resolution breaks, every rule becomes false positive.
 * - doNotFollow drift → depcruise descends into node_modules → scan
 *   wall-time explodes + false positives from dep internals.
 * - exclude drift → tests / scripts / dist get scanned → meaningless
 *   violations spam (test code intentionally violates rules for fixtures).
 *
 * Pairs with phase 1301 (tsPreCompilationDeps invariant), phase 595
 * (forbidden rule from.path), phase 599 (forbidden rule to/orphan).
 */
describe('depcruise options baseline invariant (phase 615)', () => {
  it('tsConfig.fileName + doNotFollow.path + exclude.path match baseline', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      options?: {
        tsConfig?: { fileName?: string };
        doNotFollow?: { path?: string };
        exclude?: { path?: string };
      };
    };
    const opts = cfg.options ?? {};
    expect(opts.tsConfig?.fileName).toBe('tsconfig.json');
    expect(opts.doNotFollow?.path).toBe('node_modules');
    expect(opts.exclude?.path).toBe('^(tests|scripts|dist|node_modules)');
  });
});
});

describe('depcruise-top-level-keys-invariant', () => {

/**
 * phase 659: invariant that depcruise config has exactly {forbidden,
 * options} as top-level keys — no `allowed[]` (allowlist) or other
 * model fields.
 *
 * Rationale (ML#3 single model): chestnut adopts the forbidden-only
 * model — explicit denylist, anything not denied is allowed. Mixing in
 * `allowed[]` (denylist) or other depcruise features (extends, etc.)
 * creates rule-priority ambiguity:
 * - same dep matching one forbidden + one allowed → which wins?
 * - rules silently override each other; debug becomes guesswork
 *
 * Pairs with phase 615 (options baseline), phase 633 (severity=error
 * default), phase 595 (from.path), phase 599 (to/orphan).
 */
describe('depcruise config top-level keys invariant (phase 659)', () => {
  it('top-level keys === {forbidden, options}', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as Record<string, unknown>;
    const keys = new Set(Object.keys(cfg));
    expect([...keys].sort()).toEqual(['forbidden', 'options']);
  });
});
});

describe('depcruise-cli-protocol-boundary-rules', () => {

// @ts-ignore — CJS config loaded in ESM test context


/**
 * dependency-cruiser: CLIProtocol boundary rules（phase 1253 Step D）
 *
 * 反向 fixture：验证规则 from/to shape（不只验证 rule name 存在）——
 * 若 future 静默改 from/to 范围（放宽或误伤 cli-protocol 内部 import），本组失败。
 *
 * 配对实测（phase 1253 Step D 验收时执行）：
 * - 临时让 src/cli-protocol/* import '../assembly/index.js' → lint:arch 必失败
 * - 临时让 src/assembly/* import 旧 '../cli/help/index.js' → 规则/不存在路径至少一道失败
 */
describe('dependency-cruiser: CLIProtocol boundary rules (phase 1253 Step D)', () => {
  const srcDir = path.join(process.cwd(), 'src');

  function directoriesWithOwnIndex(parentDir: string): string[] {
    return fs.readdirSync(parentDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => fs.existsSync(path.join(parentDir, name, 'index.ts')));
  }

  function expectedProductionModuleRoots(): string[] {
    const grouped = ['core', 'foundation'].flatMap((group) =>
      directoriesWithOwnIndex(path.join(srcDir, group)).map((name) => `${group}/${name}`),
    );
    const topLevel = directoriesWithOwnIndex(srcDir)
      .filter((name) => name !== 'core' && name !== 'foundation');
    return [...grouped, ...topLevel].sort();
  }

  function barrelRuleName(moduleRoot: string): string {
    return `no-deep-into-module-${moduleRoot.replace(/[\/_]/g, '-')}`;
  }

  it('no-cli-protocol-to-outside present with exact from/to shape', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'no-cli-protocol-to-outside',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.path).toBe('^src/cli-protocol/');
    expect(rule.to.path).toBe('^src/(?!cli-protocol/)');
  });

  it('no-outside-to-cli-process covers every production owner (phase 1346)', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'no-outside-to-cli-process',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('error');
    expect(rule.from.path).toBe('^src/');
    expect(rule.from.pathNot).toEqual(['^src/cli/']);
    expect(rule.to.path).toBe('^src/cli/');
  });

  it('every production module root has the same generated barrel-only error rule (phase 1348)', () => {
    const moduleRoots = expectedProductionModuleRoots();
    for (const owner of moduleRoots) {
      const rule = config.forbidden.find(
        (r: { name: string }) => r.name === barrelRuleName(owner),
      );
      expect(rule?.severity).toBe('error');
      expect(rule?.from).toEqual({ path: '^src/', pathNot: [`^src/${owner}/`] });
      expect(rule?.to.path).toBe(`^src/${owner}/(?!index\\.ts$).+`);
    }

    const generatedNames = config.forbidden
      .filter((r: { name: string }) => r.name.startsWith('no-deep-into-module-'))
      .map((r: { name: string }) => r.name)
      .sort();
    expect(generatedNames).toEqual(moduleRoots.map(barrelRuleName).sort());
    expect(new Set(generatedNames).size).toBe(generatedNames.length);
  });

  it('module discovery covers CLIProcess but not nested implementation or resource directories', () => {
    const generatedNames = config.forbidden.map((r: { name: string }) => r.name);
    expect(generatedNames).toContain('no-deep-into-module-cli');
    expect(generatedNames).toContain('no-outside-to-cli-process');
    expect(generatedNames).not.toContain('no-deep-into-module-assembly-guidance');
    expect(generatedNames).not.toContain('no-deep-into-module-core-claw-topology-jobs-outbox-summary');
    expect(generatedNames).not.toContain('no-deep-into-module-templates-prompts');
    expect(generatedNames).not.toContain('no-deep-into-module-skills');
  });

  it('no-assembly-to-cli-command-protocol-internals 已退役（phase 1283 Step B：被零边规则严格覆盖）', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'no-assembly-to-cli-command-protocol-internals',
    );
    expect(rule).toBeUndefined();
  });
});
});

describe('depcruise-tspre-and-orphan-config', () => {

// @ts-ignore — CJS config loaded in ESM test context


/**
 * dependency-cruiser config: phase 1301 tsPreCompilationDeps + no-orphans
 *
 * 反向：防 dep-cruise config silent 改 tsPreCompilationDeps 或 no-orphans rule
 * (mirror phase 1298 vitest config sync test 模式扩到 orphan detection 维度)
 *
 * 若 future 升 no-orphans severity warn → error → 必同时更新本 test + design row
 */
describe('dependency-cruiser config: phase 1301 tsPreCompilationDeps + no-orphans', () => {
  it('tsPreCompilationDeps enabled for TS type-only import tracking', () => {
    expect(config.options).toBeDefined();
    expect(config.options.tsPreCompilationDeps).toBe(true);
  });

  it('no-orphans rule present at warn severity with allowlist', () => {
    const rule = config.forbidden.find(
      (r: { name: string }) => r.name === 'no-orphans',
    );
    expect(rule).toBeDefined();
    expect(rule.severity).toBe('warn');
    expect(rule.from.orphan).toBe(true);
    expect(rule.from.pathNot).toContain('\\.d\\.ts$');
    expect(rule.from.pathNot).toContain('^src/index\\.ts$');
    expect(rule.from.pathNot).toContain('^\\.config/');
  });
});
});
