// Auto-generated by Phase 1008 Step C: merged arch invariant tests.
// Do not edit manually; edit the original per-topic tests instead.

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import config from '../../../.config/dependency-cruiser.cjs';

describe('eslint-config-imports-deps-invariant', () => {

/**
 * phase 646: invariant that every non-local import in .config/eslint.config.js
 * resolves to a package in package.json (dependencies ∪ devDependencies).
 *
 * Rationale (ML#9 explicit coupling): config literal imports + package.json
 * deps are an inescapable coupling. Drift breaks at runtime:
 * - add new plugin import but forget deps → install succeeds, `pnpm
 *   lint:lint` throws `Cannot find module` at config load
 * - remove deps but config keeps import → same throw
 *
 * One-way: config → package.json. Reverse (deps not used in config)
 * is covered by phase 511 no-unused-node-modules depcruise rule.
 *
 * Normalizes import specifiers to package roots:
 * - `pkg` → `pkg`
 * - `pkg/sub/path` → `pkg`
 * - `@scope/name/sub` → `@scope/name`
 *
 * Pairs with phase 616 (eslint config languageOptions baseline), phase
 * 591 (3-way rule pairing), phase 511 (no-unused-node-modules).
 */
describe('eslint.config imports ⊆ package deps invariant (phase 646)', () => {
  it('every non-local import resolves to package.json dep', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const cfgText = fs.readFileSync(
      path.join(repoRoot, '.config/eslint.config.js'),
      'utf-8',
    );
    const pkg = JSON.parse(
      fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf-8'),
    ) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const allDeps = new Set([
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ]);

    const importRe = /^import\s+[\s\S]*?from\s+['"]([^'"]+)['"]/gm;
    const offenders: string[] = [];
    const toPkgRoot = (spec: string): string => {
      if (spec.startsWith('@')) {
        const parts = spec.split('/');
        return parts.slice(0, 2).join('/');
      }
      return spec.split('/')[0];
    };

    let m: RegExpExecArray | null;
    while ((m = importRe.exec(cfgText)) !== null) {
      const spec = m[1];
      if (spec.startsWith('.')) continue; // local import
      const pkgRoot = toPkgRoot(spec);
      if (!allDeps.has(pkgRoot)) {
        offenders.push(`${spec} (root=${pkgRoot}) not in package.json deps`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-config-language-options-invariant', () => {

/**
 * phase 616: invariant that .config/eslint.config.js main config object
 * has the baseline languageOptions:
 * - files === ['src/**\/*.ts']
 * - languageOptions.parserOptions.ecmaVersion === 'latest'
 * - languageOptions.parserOptions.sourceType === 'module'
 * - languageOptions.parserOptions.project === './tsconfig.json'
 *
 * Rationale: ESLint flat config languageOptions is the parser/AST baseline.
 * - files drift → miss / over-scan .ts files
 * - ecmaVersion drift → parser misses new syntax → false errors
 * - sourceType drift → module/script flip, import/export parse breaks
 * - project drift → type-aware typescript-eslint rules silently fallback
 *   to no-type mode → false-green warnings
 *
 * The main config is identified by presence of plugins['chestnut-custom']
 * (the chestnut-custom rule registration block).
 *
 * Pairs with phase 615 (depcruise options), phase 608 (tsconfig strict),
 * phase 596 (rule meta.type), phase 591 (3-way pairing).
 */
type EslintConfig = {
  files?: unknown;
  languageOptions?: {
    parserOptions?: {
      ecmaVersion?: unknown;
      sourceType?: unknown;
      project?: unknown;
    };
  };
  plugins?: Record<string, unknown>;
};

describe('eslint.config languageOptions baseline invariant (phase 616)', () => {
  it('main config has files + parserOptions baseline', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const cfgPath = path.join(repoRoot, '.config/eslint.config.js');
    const mod = (await import(cfgPath)) as { default?: unknown };
    const raw = mod.default;
    const cfgs: EslintConfig[] = Array.isArray(raw) ? (raw as EslintConfig[]) : [];
    expect(cfgs.length).toBeGreaterThan(0);

    const main = cfgs.find(c => c.plugins && 'chestnut-custom' in c.plugins);
    expect(main).toBeDefined();
    const m = main as EslintConfig;
    expect(m.files).toEqual(['src/**/*.ts']);
    const po = m.languageOptions?.parserOptions ?? {};
    expect(po.ecmaVersion).toBe('latest');
    expect(po.sourceType).toBe('module');
    expect(po.project).toBe('./tsconfig.json');
  });
});
});

describe('eslint-config-plugins-invariant', () => {

/**
 * phase 657: invariant that the main eslint config object registers both
 * `@typescript-eslint` and `chestnut-custom` in its `plugins:` block.
 *
 * Rationale (ML#3 single-source rule hosting):
 * - missing `@typescript-eslint` → type-aware rules can't load (even if
 *   none enabled currently, the parser+plugin pair is required for
 *   tsParser to work end-to-end)
 * - missing `chestnut-custom` → all 32 chestnut-custom rules silently
 *   stop firing
 *
 * Doesn't lock plugins to exactly these 2 — allows future addition of
 * other plugins.
 *
 * Pairs with phase 591 (3-way plugin/rules pairing), phase 616
 * (languageOptions baseline), phase 596 (meta.type=problem).
 */
type EslintConfig = { plugins?: Record<string, unknown> };

describe('eslint.config plugins set invariant (phase 657)', () => {
  it('main config registers @typescript-eslint + chestnut-custom plugins', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const cfgPath = path.join(repoRoot, '.config/eslint.config.js');
    const mod = (await import(cfgPath)) as { default?: unknown };
    const raw = mod.default;
    const cfgs: EslintConfig[] = Array.isArray(raw) ? (raw as EslintConfig[]) : [];
    expect(cfgs.length).toBeGreaterThan(0);

    const main = cfgs.find(c => c.plugins && 'chestnut-custom' in c.plugins);
    expect(main, 'no config object with chestnut-custom plugin').toBeDefined();

    const plugins = (main as EslintConfig).plugins ?? {};
    const REQUIRED = ['@typescript-eslint', 'chestnut-custom'];
    const missing = REQUIRED.filter(p => !(p in plugins));
    expect(missing).toEqual([]);
  });
});
});

describe('eslint-rule-category-invariant', () => {

/**
 * phase 663: invariant that every chestnut-custom rule has
 * `meta.docs.category === 'Best Practices'`.
 *
 * Rationale (ML#3 single-source classification): chestnut-custom rules
 * are architectural constraints — Best Practices category. They are NOT
 * Possible Errors (runtime-error-class) or Stylistic Issues (cosmetic).
 * Drift breaks invisibly:
 * - IDE rule browsers / filters group rules by category; mis-classified
 *   rules invisible under expected filter
 * - lint report grouping mismatches user expectation
 *
 * Pairs with phase 596 (meta.type='problem'), phase 597 (structural
 * quartet), phase 598 (应然 marker), phase 603 (description non-empty).
 */
describe('ESLint rule meta.docs.category invariant (phase 663)', () => {
  it('every rule has meta.docs.category === "Best Practices"', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { docs?: { category?: string } } };
      };
      const cat = mod?.default?.meta?.docs?.category;
      if (cat !== 'Best Practices') {
        offenders.push(`${f}: category=${String(cat)}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-context-report-messageid-only-invariant', () => {

/**
 * phase 668: invariant that every chestnut-custom rule uses
 * `context.report({ ..., messageId: '...' })` and NOT the legacy
 * `context.report({ message: '<inline>', ... })` pattern.
 *
 * Rationale (ML#9 explicit coupling):
 * - inline `message:` decouples report text from meta.messages SoT;
 *   phase 607 messageId set-equivalence invariant can't catch it
 * - i18n impossible (messageId is the i18n key)
 * - ESLint 8+ best-practice is messageId-only
 *
 * Pairs with phase 607 (messageId set-equivalence), phase 604 (messages
 * non-empty), phase 617 (messageId camelCase), phase 666 (export keys
 * strict), phase 597 (structural quartet).
 */
describe('ESLint rule context.report messageId-only invariant (phase 668)', () => {
  it('every rule uses context.report + no inline message:', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const missingReport: string[] = [];
    const inlineMessage: string[] = [];
    // matches context.report({...message:...) — non-greedy with [\s\S] for
    // multi-line option objects.
    const inlineRe = /context\.report[\s\S]*?\bmessage:/;
    for (const f of files) {
      const text = fs.readFileSync(path.join(rulesDir, f), 'utf-8');
      if (!text.includes('context.report')) missingReport.push(f);
      if (inlineRe.test(text)) inlineMessage.push(f);
    }
    expect(missingReport).toEqual([]);
    expect(inlineMessage).toEqual([]);
  });
});
});

describe('eslint-rule-count-ratchet', () => {

/**
 * phase 631: ratchet test for chestnut-custom ESLint rule count.
 *
 * 当前 32 rule、ratchet 下限 30（buffer 2 防偶发临时去除）。新增 rule 时持续
 * 调高下限、防 future 误删 rule（rebase 错位 / merge 漏 / refactor 失误）→
 * rule 集成静默缩水、编码规约失防。
 *
 * Mirrors phase 494/563 `depcruise-rule-count-ratchet` (≥ 50 forbidden
 * rules) for the ESLint custom rules surface.
 *
 * Pairs with phase 580 (rule ↔ test 1:1), phase 591 (3-way pairing),
 * phase 593 (severity), phase 596 (meta.type), phase 597 (quartet).
 */
describe('ESLint custom rule count ratchet (phase 631)', () => {
  it('chestnut-custom rule files count ≥ 30', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs.readdirSync(rulesDir).filter(f => f.endsWith('.js'));
    expect(files.length).toBeGreaterThanOrEqual(30);
  });
});
});

describe('eslint-rule-create-signature-invariant', () => {

/**
 * phase 680: invariant that every chestnut-custom rule .js source has
 * `create(context)` as a regular method (not arrow function) and
 * returns a visitor object via `return {`.
 *
 * Rationale (ML#3 single-source signature): ESLint rule create signature
 * is the call contract. chestnut-custom standardizes regular method
 * `create(context) { ... }` with parameter `context`. Drift to:
 * - arrow `create: (context) =>` → ESLint semantics same (this binding
 *   irrelevant) but style fragments
 * - parameter rename `ctx` / `_context` → grep / refactor drift
 *
 * Pairs with phase 597 (structural quartet — create present), phase
 * 596 (meta.type='problem'), phase 665 (meta keys strict), phase 666
 * (export keys strict).
 */
describe('ESLint rule create signature invariant (phase 680)', () => {
  it('every rule has create(context) regular method + return {', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const createRe = /\bcreate\s*\(\s*context\s*\)/;
    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(rulesDir, f), 'utf-8');
      if (!createRe.test(text)) offenders.push(`${f}: no create(context)`);
      if (!text.includes('return {')) offenders.push(`${f}: no return {`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-description-invariant', () => {

/**
 * phase 603: invariant that every chestnut-custom ESLint rule under
 * .config/eslint-rules/*.js has `meta.docs.description` as a non-empty
 * trimmed string.
 *
 * Rationale: meta.docs.description is the SoT for IDE hover hints +
 * human-readable lint report messages. Empty / missing description → the
 * developer sees the rule fire but no explanation of intent → rule decays
 * into a black-box "punish but don't tell you why" punisher.
 *
 * Extends phase 597 (meta.docs presence) with content-level non-empty
 * constraint. Pairs with phase 598 (应然 marker in header), phase 596
 * (meta.type='problem'), phase 593 (severity='error').
 */
describe('ESLint chestnut-custom rule description invariant (phase 603)', () => {
  it('every rule has meta.docs.description as non-empty string', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { docs?: { description?: unknown } } };
      };
      const desc = mod?.default?.meta?.docs?.description;
      if (typeof desc !== 'string' || desc.trim().length === 0) {
        offenders.push(`${f}: description=${String(desc)}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-description-length-invariant', () => {

/**
 * phase 661: invariant that every chestnut-custom rule's
 * `meta.docs.description` is at least 20 characters long.
 *
 * Rationale: description is the SoT for IDE hover hint + lint report
 * narrative. Trivial description like 'rule x' leaves user knowing only
 * that the rule fired, not why or how to fix.
 *
 * Loose floor (20 chars) — current shortest is 59 chars; catches
 * accidental trim/clip without dictating long-form prose.
 *
 * Mirrors phase 660 (depcruise rule comment length ≥ 30) for the ESLint
 * description surface. Pairs with phase 603 (non-empty), phase 636
 * (unique).
 */
describe('ESLint rule description length invariant (phase 661)', () => {
  it('every meta.docs.description length ≥ 20', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { docs?: { description?: string } } };
      };
      const desc = mod?.default?.meta?.docs?.description ?? '';
      if (desc.length < 20) {
        offenders.push(`${f} (len=${desc.length})`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-description-unique-invariant', () => {

/**
 * phase 636: invariant that every chestnut-custom ESLint rule's
 * `meta.docs.description` is unique — no two rules share the same
 * description.
 *
 * Rationale (ML#3 single-source semantics): each rule's description is
 * the SoT for that rule's purpose (shown in IDE hover hints + lint
 * report). Drift breaks invisibly when copy-paste leaves two rules
 * sharing a description:
 * - IDE hover hint identifies different rules with same text
 * - delete one rule but description was the working SoT for another →
 *   intent lost on the survivor
 *
 * Mirrors phase 635 (depcruise comment uniqueness) for the ESLint
 * description surface. Pairs with phase 603 (description non-empty),
 * phase 617 (messageId camelCase), phase 607 (messageId set-equivalence).
 */
describe('ESLint rule description uniqueness invariant (phase 636)', () => {
  it('every rule meta.docs.description is unique', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const seen = new Map<string, string>();
    const duplicates: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { docs?: { description?: string } } };
      };
      const desc = mod?.default?.meta?.docs?.description ?? '';
      if (seen.has(desc)) {
        duplicates.push(`${f} ↔ ${seen.get(desc)} (shared: ${desc.slice(0, 60)}…)`);
      } else {
        seen.set(desc, f);
      }
    }
    expect(duplicates).toEqual([]);
  });
});
});

describe('eslint-rule-docs-keys-strict-invariant', () => {

/**
 * phase 664: invariant that every chestnut-custom rule's `meta.docs`
 * has exactly the keys {description, category} — no extra fields like
 * url, recommended, requiresTypeChecking, etc.
 *
 * Rationale (ML#3 single-source docs shape): chestnut-custom rule docs
 * structure should be uniform (description + category). Additional
 * optional fields (url, recommended) — if needed — should be added
 * across all rules in one phase + accompanied by their own invariant,
 * not ad-hoc per-rule additions that fragment docs shape.
 *
 * Pairs with phase 597 (structural quartet), phase 603 (description
 * non-empty), phase 663 (category = 'Best Practices'), phase 636
 * (description uniqueness).
 */
describe('ESLint rule meta.docs keys strict invariant (phase 664)', () => {
  it('every meta.docs has exactly keys {description, category}', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const EXPECTED = ['category', 'description'];
    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { docs?: Record<string, unknown> } };
      };
      const docs = mod?.default?.meta?.docs ?? {};
      const actual = Object.keys(docs).sort();
      if (JSON.stringify(actual) !== JSON.stringify(EXPECTED)) {
        offenders.push(`${f}: keys=${actual.join(',')}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-esm-export-default-invariant', () => {

/**
 * phase 667: invariant that every chestnut-custom rule .js source file
 * contains exactly one top-level `export default ` line (ESM syntax).
 *
 * Rationale (ML#3 single-source export form): ESLint flat config loads
 * rule modules via `await import()`. ESM `export default` is the
 * contract. Drift breaks invisibly:
 * - swap to `module.exports = ` (CJS) → dynamic import sees default
 *   wrapped under .default property mismatch, rule fails to load (or
 *   loads as undefined → ESLint silently skips it)
 * - more than one `export default` → SyntaxError at load
 *
 * phase 666 covered default export shape ({meta, create}); this phase
 * verifies the export FORM (ESM single default) at the source layer.
 *
 * Pairs with phase 666 (export keys strict), phase 665 (meta keys
 * strict), phase 597 (structural quartet).
 */
describe('ESLint rule ESM export default invariant (phase 667)', () => {
  it('every rule .js has exactly 1 top-level `export default ` line', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    const re = /^export default /gm;
    for (const f of files) {
      const text = fs.readFileSync(path.join(rulesDir, f), 'utf-8');
      const matches = text.match(re) ?? [];
      if (matches.length !== 1) {
        offenders.push(`${f}: ${matches.length} 'export default' lines`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-export-keys-strict-invariant', () => {

/**
 * phase 666: invariant that every chestnut-custom rule's default export
 * has exactly {meta, create} as keys — no extra fields like
 * defaultOptions, configs, etc.
 *
 * Rationale (ML#3 single-source export shape): rule export is the
 * outermost ESLint loading surface. Structure must be uniform. Any
 * extra field should be added across all rules in one phase + own
 * invariant.
 *
 * Mirrors phase 664 (meta.docs keys strict) + phase 665 (meta keys
 * strict) at the default export layer above. Together these 3 phases
 * pin all 3 levels of rule structure.
 *
 * Pairs with phase 597 (structural quartet — presence), phase 596
 * (meta.type='problem'), phase 665 (meta keys strict).
 */
describe('ESLint rule export keys strict invariant (phase 666)', () => {
  it('every default export has exactly keys {meta, create}', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const EXPECTED = ['create', 'meta'];
    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: Record<string, unknown>;
      };
      const exp = mod?.default ?? {};
      const actual = Object.keys(exp).sort();
      if (JSON.stringify(actual) !== JSON.stringify(EXPECTED)) {
        offenders.push(`${f}: keys=${actual.join(',')}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-filename-kebab-case-invariant', () => {

/**
 * phase 648: invariant that every chestnut-custom ESLint rule filename
 * (basename without .js) matches kebab-case
 * `/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/`.
 *
 * Rationale: ESLint community convention (mirrored by upstream rules
 * like `no-unused-vars`, `no-empty-function`) standardizes rule names on
 * kebab-case. chestnut-custom follows this convention — drift to
 * camelCase / PascalCase / snake_case fragments grep, IDE autocomplete,
 * and creates ambiguity between rule key (plugin.rules['<name>']) and
 * rule file basename.
 *
 * Pairs with phase 580 (rule ↔ test 1:1), phase 591 (3-way pairing),
 * phase 617 (messageId camelCase), phase 606 (run name === basename).
 */
describe('ESLint custom rule filename kebab-case invariant (phase 648)', () => {
  it('every rule basename matches /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs.readdirSync(rulesDir).filter(f => f.endsWith('.js'));
    const kebab = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
    const offenders: string[] = [];
    for (const f of files) {
      const basename = f.replace(/\.js$/, '');
      if (!kebab.test(basename)) offenders.push(basename);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-line-count-ratchet', () => {

/**
 * phase 670: ratchet test that every chestnut-custom ESLint rule .js
 * file has line count ≤ 300.
 *
 * 当前最长 239 行（foundation-no-business-role-literal.js）。soft
 * ceiling 300、buffer ≥ 60 防偶发临时长。新增 rule 增长跨越 300 → review
 * 时强制思考拆分（ML#7 模块界面最小、单一职责）。
 *
 * Pairs with phase 631 (rule count ratchet ≥ 30), phase 632 (arch
 * test count ratchet ≥ 20).
 */
describe('ESLint rule line count ratchet (phase 670)', () => {
  it('every rule .js file line count ≤ 300', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs.readdirSync(rulesDir).filter(f => f.endsWith('.js'));
    const offenders: string[] = [];
    for (const f of files) {
      const lines = fs.readFileSync(path.join(rulesDir, f), 'utf-8').split('\n').length;
      if (lines > 300) offenders.push(`${f} (${lines} lines)`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-message-length-invariant', () => {

/**
 * phase 662: invariant that every chestnut-custom rule's
 * `meta.messages` value is at least 30 characters long.
 *
 * Rationale: message value is the SoT for ESLint report text. Trivial
 * value like 'X' leaves user knowing rule fired but not why or how to
 * fix.
 *
 * Loose floor 30 chars — current shortest is 84 chars; catches
 * accidental clip without dictating long-form prose.
 *
 * Pairs with phase 604 (non-empty), phase 637 (unique), phase 617 (key
 * camelCase), phase 661 (description length).
 */
describe('ESLint rule message length invariant (phase 662)', () => {
  it('every meta.messages value length ≥ 30', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { messages?: Record<string, string> } };
      };
      const messages = mod?.default?.meta?.messages ?? {};
      for (const [k, v] of Object.entries(messages)) {
        if (v.length < 30) offenders.push(`${f}:${k} (len=${v.length})`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-message-value-unique-invariant', () => {

/**
 * phase 637: invariant that every chestnut-custom rule's
 * `meta.messages` *value* (the report text) is unique across all rules.
 *
 * Rationale (ML#3 single-source error text): each message value is the
 * SoT for ESLint report text. Drift breaks invisibly when copy-paste
 * leaves two rules sharing a value:
 * - developer sees "rule X: <text>" in lint output, but X may have been
 *   triggered by either rule's logic — debugging path becomes guesswork
 * - subtle bugs hide: if rule A is broken but rule B fires the same
 *   text, no observable signal that A was supposed to catch something
 *
 * Pairs with phase 604 (messages non-empty), phase 617 (messageId
 * camelCase), phase 607 (messageId set-equivalence), phase 636
 * (description uniqueness).
 */
describe('ESLint rule message value uniqueness invariant (phase 637)', () => {
  it('every meta.messages value is unique across all rules', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const seen = new Map<string, string>();
    const duplicates: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { messages?: Record<string, string> } };
      };
      const messages = mod?.default?.meta?.messages ?? {};
      for (const [k, v] of Object.entries(messages)) {
        const ref = `${f}:${k}`;
        if (seen.has(v)) {
          duplicates.push(`${ref} ↔ ${seen.get(v)} (shared: ${v.slice(0, 60)}…)`);
        } else {
          seen.set(v, ref);
        }
      }
    }
    expect(duplicates).toEqual([]);
  });
});
});

describe('eslint-rule-messageid-camelcase-invariant', () => {

/**
 * phase 617: invariant that every chestnut-custom ESLint rule's
 * `meta.messages` keys use camelCase naming.
 *
 * Rationale: ESLint convention (mirrored by upstream rules like
 * no-unused-vars / unusedVar) standardizes messageId on camelCase. Mixing
 * kebab-case / snake_case / PascalCase fragments grep / IDE autocomplete
 * and creates ambiguity at `context.report({ messageId })` call sites.
 *
 * Pairs with phase 607 (messageId set equivalence), phase 604 (messages
 * non-empty), phase 603 (description non-empty), phase 597 (structural
 * quartet).
 */
describe('ESLint rule messageId camelCase invariant (phase 617)', () => {
  it('every meta.messages key matches camelCase /^[a-z][a-zA-Z0-9]*$/', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    const camelCase = /^[a-z][a-zA-Z0-9]*$/;
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { messages?: Record<string, unknown> } };
      };
      const messages = mod?.default?.meta?.messages ?? {};
      for (const k of Object.keys(messages)) {
        if (!camelCase.test(k)) offenders.push(`${f}: '${k}' not camelCase`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-messageid-pairing-invariant', () => {

/**
 * phase 607: invariant that every chestnut-custom ESLint rule's
 * `meta.messages` declared keys set equals the set of `messageId:` references
 * in the rule source.
 *
 * Rationale (ML#9 explicit coupling): meta.messages declarations + create
 * body context.report({ messageId }) references are an inescapable coupling.
 * Drift breaks invisibly:
 * - declared ⊃ referenced → dead message keys, missed when removing rule
 *   variant, accumulate as cruft.
 * - referenced ⊄ declared → typo or undeclared messageId; ESLint falls back
 *   to '' or undefined-key handling at runtime, masking the actual report.
 *
 * Pairs with phase 604 (messages non-empty), phase 597 (meta.messages
 * presence), phase 587 (RuleTester), phase 605 (valid/invalid non-empty).
 */
describe('ESLint rule messageId set-equivalence invariant (phase 607)', () => {
  it('every rule meta.messages keys === messageId references in source', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    const messageIdRe = /messageId:\s*['"]([^'"]+)['"]/g;
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const src = fs.readFileSync(rulePath, 'utf-8');
      const mod = (await import(rulePath)) as {
        default?: { meta?: { messages?: Record<string, unknown> } };
      };
      const declared = new Set(Object.keys(mod?.default?.meta?.messages ?? {}));
      const referenced = new Set<string>();
      let m: RegExpExecArray | null;
      while ((m = messageIdRe.exec(src)) !== null) referenced.add(m[1]);
      messageIdRe.lastIndex = 0;

      const unused = [...declared].filter(k => !referenced.has(k));
      const undeclared = [...referenced].filter(k => !declared.has(k));
      if (unused.length > 0)
        offenders.push(`${f}: unused declared messageId(s): ${unused.join(', ')}`);
      if (undeclared.length > 0)
        offenders.push(`${f}: undeclared referenced messageId(s): ${undeclared.join(', ')}`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-messages-non-empty-invariant', () => {

/**
 * phase 604: invariant that every entry in `meta.messages` of every
 * chestnut-custom ESLint rule is a non-empty trimmed string.
 *
 * Rationale: meta.messages is the SoT for ESLint report text — context.report
 * lookups consume this map by messageId. Empty / undefined / non-string entry
 * → developer sees the rule fire but no explanatory text → black-box
 * punisher (same shape as phase 603 description failure mode, different
 * surfacing channel).
 *
 * Extends phase 597 (meta.messages presence) with content-level non-empty
 * constraint. Pairs with phase 603 (description non-empty), phase 598
 * (应然 marker), phase 596 (meta.type='problem').
 */
describe('ESLint chestnut-custom rule messages non-empty invariant (phase 604)', () => {
  it('every meta.messages value is non-empty string', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { messages?: Record<string, unknown> } };
      };
      const messages = mod?.default?.meta?.messages ?? {};
      for (const [k, v] of Object.entries(messages)) {
        if (typeof v !== 'string' || v.trim().length === 0) {
          offenders.push(`${f}:${k}=${String(v)}`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-meta-keys-strict-invariant', () => {

/**
 * phase 665: invariant that every chestnut-custom rule's `meta` has
 * exactly {type, docs, schema, messages} as keys — no extra fields like
 * fixable, hasSuggestions, deprecated, replacedBy.
 *
 * Rationale (ML#3 single-source meta shape): chestnut-custom rule meta
 * structure should be uniform. Additional ESLint meta fields (fixable,
 * etc.) — if needed — should be added across all rules in one phase +
 * accompanied by their own invariant.
 *
 * Mirrors phase 664 (meta.docs keys strict) at the meta layer above.
 * Pairs with phase 597 (structural quartet — presence), phase 596
 * (meta.type='problem'), phase 664 (docs keys strict).
 */
describe('ESLint rule meta keys strict invariant (phase 665)', () => {
  it('every meta has exactly keys {type, docs, schema, messages}', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const EXPECTED = ['docs', 'messages', 'schema', 'type'];
    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: Record<string, unknown> };
      };
      const meta = mod?.default?.meta ?? {};
      const actual = Object.keys(meta).sort();
      if (JSON.stringify(actual) !== JSON.stringify(EXPECTED)) {
        offenders.push(`${f}: keys=${actual.join(',')}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-meta-type-invariant', () => {

/**
 * phase 596: invariant that every chestnut-custom ESLint rule under
 * .config/eslint-rules/*.js exports `meta.type === 'problem'`.
 *
 * Rationale: all chestnut-custom rules encode architectural / coding standard
 * violations (M#5 unidirectional dep, M#3 ownership, M#7 boundary, coding
 * conventions) — never cosmetic suggestions or layout style. Drifting to
 * 'suggestion' or 'layout' would weaken IDE surfacing + miscategorize the
 * intent of the rule.
 *
 * Pairs with phase 587 (rule test uses RuleTester), phase 589 (rule ↔ config
 * import 1:1), phase 591 (3-way plugin/rules pairing), phase 593 (severity
 * = 'error'), phase 585 (phase reference in rule + test).
 */
describe('ESLint chestnut-custom rule meta.type invariant (phase 596)', () => {
  it('every .config/eslint-rules/*.js has meta.type === "problem"', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { type?: string } };
      };
      const type = mod?.default?.meta?.type;
      if (type !== 'problem') offenders.push(`${f}: meta.type=${String(type)}`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-schema-empty-invariant', () => {

/**
 * phase 669: invariant that every chestnut-custom rule has
 * `meta.schema === []` (empty array — no user options accepted).
 *
 * Rationale (ML#3 single-source rule config): chestnut-custom rules are
 * repo-internal — caller doesn't customize them. Introducing schema:
 * - allows eslint.config.js to pass options per call site → double SoT
 *   (rule source + config) → complexity explosion
 * - i18n / mock contexts become harder
 *
 * phase 597 covers schema presence (any value); this phase pins it to
 * the empty-array default, complementary.
 *
 * Pairs with phase 597 (structural quartet — presence), phase 596
 * (meta.type='problem'), phase 665 (meta keys strict), phase 666
 * (export keys strict).
 */
describe('ESLint rule meta.schema empty invariant (phase 669)', () => {
  it('every meta.schema deepEqual []', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: { meta?: { schema?: unknown } };
      };
      const schema = mod?.default?.meta?.schema;
      if (!Array.isArray(schema) || schema.length !== 0) {
        offenders.push(`${f}: schema=${JSON.stringify(schema)}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-structure-completeness-invariant', () => {

/**
 * phase 597: invariant that every chestnut-custom ESLint rule under
 * .config/eslint-rules/*.js exports the structural quartet:
 *
 *   1. `meta.docs`     — human-readable description (IDE surfacing).
 *   2. `meta.schema`   — option validation; missing → options silently dropped.
 *   3. `meta.messages` — messageId mechanism; missing → context.report inline
 *                        string literals, breaking i18n + lint:lint quality bar.
 *   4. `create`        — visitor factory; missing → ESLint rule load failure.
 *
 * Pairs with phase 596 (meta.type='problem'), phase 593 (severity), phase 591
 * (3-way plugin/rules pairing), phase 589 (rule ↔ config import), phase 587
 * (RuleTester), phase 585 (phase reference).
 */
describe('ESLint chestnut-custom rule structural completeness (phase 597)', () => {
  it('every rule has meta.docs + meta.schema + meta.messages + create', async () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const rulePath = path.join(rulesDir, f);
      const mod = (await import(rulePath)) as {
        default?: {
          meta?: { docs?: unknown; schema?: unknown; messages?: unknown };
          create?: unknown;
        };
      };
      const rule = mod?.default;
      const missing: string[] = [];
      if (!rule?.meta?.docs) missing.push('meta.docs');
      if (!rule?.meta?.schema) missing.push('meta.schema');
      if (!rule?.meta?.messages) missing.push('meta.messages');
      if (typeof rule?.create !== 'function') missing.push('create');
      if (missing.length > 0) offenders.push(`${f}: missing ${missing.join(', ')}`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-canonical-import-invariant', () => {

/**
 * phase 673: invariant that every chestnut-custom rule test file uses
 * the canonical import form:
 *
 *   import { RuleTester } from 'eslint';
 *
 * Rationale (ML#3 single-source import form): rule test import form
 * must be uniform for grep / refactor reliability. Drift to
 * `import * as eslint from 'eslint'; eslint.RuleTester`, namespace
 * aliases, or destructured renames fragments search/replace.
 *
 * phase 587 covers test contains 'RuleTester' literal; this phase pins
 * the exact import line, complementary.
 *
 * Pairs with phase 587 (RuleTester usage required), phase 671 (no
 * vi.mock), phase 672 (describe label), phase 628 (rule import path).
 */
const CANONICAL = "import { RuleTester } from 'eslint';";

describe('ESLint rule test canonical RuleTester import invariant (phase 673)', () => {
  it('every rule test contains canonical import line', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      if (!text.includes(CANONICAL)) offenders.push(f);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-canonical-vitest-import-invariant', () => {

/**
 * phase 674: invariant that every chestnut-custom rule test file uses
 * the canonical vitest import form:
 *
 *   import { describe, it } from 'vitest';
 *
 * Rationale (ML#3 single-source import form): rule tests don't need
 * `expect` (RuleTester contains internal assertions) or `vi` (phase 671
 * bans vi.mock). The canonical import is `{describe, it}` only.
 *
 * Mirrors phase 673 (canonical RuleTester import) to the vitest import
 * side.
 *
 * Pairs with phase 673 (canonical RuleTester import), phase 671 (no
 * vi.mock), phase 672 (describe label), phase 587 (RuleTester usage).
 */
const CANONICAL_VITEST = "import { describe, it } from 'vitest';";

describe('ESLint rule test canonical vitest import invariant (phase 674)', () => {
  it('every rule test contains canonical vitest import', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      if (!text.includes(CANONICAL_VITEST)) offenders.push(f);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-count-ratchet', () => {

/**
 * phase 651: ratchet test for tests/foundation/eslint-rules/*.test.ts
 * file count.
 *
 * 当前 32 file、ratchet 下限 30（buffer 2）。新增 rule test 时持续调高下限。
 * 防 future 误删（rebase 错位 / merge 漏 / refactor 失误）→ rule 行为可能
 * 漂但没测发现。
 *
 * Mirrors phase 631 (.config/eslint-rules count ≥ 30) + phase 632 (arch
 * test count ≥ 20) for the eslint-rule test surface. phase 580 1:1 pairing
 * binds rule + test dir counts implicitly; this ratchet provides explicit
 * lower-bound on the test side.
 */
describe('ESLint rule test count ratchet (phase 651)', () => {
  it('tests/foundation/eslint-rules/*.test.ts count ≥ 30', () => {
    const testDir = path.resolve(
      __dirname,
      '../../../tests/foundation/eslint-rules',
    );
    const files = fs.readdirSync(testDir).filter(f => f.endsWith('.test.ts'));
    expect(files.length).toBeGreaterThanOrEqual(30);
  });
});
});

describe('eslint-rule-test-describe-label-invariant', () => {

/**
 * phase 672: invariant that every chestnut-custom rule test file's
 * first describe block label starts with 'eslint custom rule'.
 *
 * Rationale (ML#3 single-source naming): rule test describe label is
 * the SoT for the chestnut-custom test set in vitest output. Drift to
 * other labels:
 * - grep 'eslint custom rule' from vitest output no longer locates the
 *   subset, debugging becomes guesswork
 * - test-set filtering by label fragments
 *
 * phase 583 covers arch test describe containing phase NNN; this phase
 * pins the specific prefix for rule tests (complementary).
 *
 * Pairs with phase 583 (arch test phase NNN reference), phase 585
 * (rule + test phase reference), phase 606 (run name === basename),
 * phase 671 (no vi.mock).
 */
describe('ESLint rule test describe label invariant (phase 672)', () => {
  it('every rule test starts with describe("eslint custom rule', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const re = /describe\(\s*['"]eslint custom rule/;
    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      if (!re.test(text)) offenders.push(f);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-import-path-pairing-invariant', () => {

/**
 * phase 628: invariant that every chestnut-custom rule test file imports
 * its rule via `from '../../../.config/eslint-rules/<basename>.js'`
 * where `<basename>` exactly matches the test file's basename (without
 * `.test.ts`).
 *
 * Rationale (ML#9 explicit coupling): the test file basename + the
 * imported rule's basename must stay synchronized. Drift breaks at test
 * load:
 * - rename rule file but forget test import → import fail loud at test
 *   collection, but only when running that suite
 * - typo in either path → same shape
 *
 * Adds a finer-grained guard layer on top of phase 580 (1:1 file pairing)
 * + phase 606 (ruleTester.run name === basename).
 *
 * Pairs with phase 606 (run name), phase 580 (file 1:1), phase 587
 * (RuleTester usage), phase 605 (valid/invalid non-empty).
 */
describe('ESLint rule test import path pairing invariant (phase 628)', () => {
  it('every test file imports rule from matching basename path', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const offenders: string[] = [];
    const importRe = /from\s+['"]\.\.\/\.\.\/\.\.\/\.config\/eslint-rules\/([^'"]+)\.js['"]/;
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      const basename = f.replace(/\.test\.ts$/, '');
      const m = text.match(importRe);
      if (!m) {
        offenders.push(`${f}: no '../../../.config/eslint-rules/<x>.js' import`);
        continue;
      }
      if (m[1] !== basename) {
        offenders.push(`${f}: imports '${m[1]}.js' (expected '${basename}.js')`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-line-count-ratchet', () => {

/**
 * phase 675: ratchet test that every chestnut-custom ESLint rule test
 * file has line count ≤ 200.
 *
 * 当前最长 152 行（no-silent-x-without-allowed-pattern.test.ts）。soft
 * ceiling 200、buffer ~50 防偶发。Rule test 应只测对应 rule、不应聚合
 * 多种约束（ML#7 模块界面最小）。
 *
 * Mirrors phase 670 (rule line count ≤ 300) to the test-file layer.
 * Pairs with phase 651 (rule test count ratchet ≥ 30).
 */
describe('ESLint rule test line count ratchet (phase 675)', () => {
  it('every rule test file line count ≤ 200', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs.readdirSync(testDir).filter(f => f.endsWith('.test.ts'));
    const offenders: string[] = [];
    for (const f of files) {
      const lines = fs.readFileSync(path.join(testDir, f), 'utf-8').split('\n').length;
      if (lines > 200) offenders.push(`${f} (${lines} lines)`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-no-vi-mock-invariant', () => {

/**
 * phase 671: invariant that no ESLint rule test file uses `vi.mock` or
 * `vi.fn(`.
 *
 * Rationale (ML#3 single-source test method): rule tests use ESLint's
 * `RuleTester` as the SoT. Layering vitest mocks on top:
 * - double abstraction breaks mock isolation guarantees
 * - vi.mock introduces hidden dependency on the mocked real module;
 *   rule behavior detaches from real ESLint runtime
 *
 * Pairs with phase 587 (RuleTester usage required), phase 605
 * (valid/invalid non-empty), phase 606 (ruleTester.run name === basename),
 * phase 628 (test import path pairing).
 */
describe('ESLint rule test no vi.mock/vi.fn invariant (phase 671)', () => {
  it('no rule test file uses vi.mock or vi.fn(', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      if (/\bvi\.mock\b/.test(text)) offenders.push(`${f}: vi.mock`);
      if (/\bvi\.fn\(/.test(text)) offenders.push(`${f}: vi.fn(`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-pairing', () => {

/**
 * phase 580: invariant test that every ESLint custom rule has a corresponding
 * RuleTester unit test, and vice versa (strict 1:1 pairing).
 *
 * Convention:
 *   .config/eslint-rules/<rule-name>.js  ↔  tests/foundation/eslint-rules/<rule-name>.test.ts
 *
 * Established by phase 309 ESLint infra + per-rule commit-time pairing.
 * Prevents future drift where a new rule is added but tests slip OR a test
 * outlives its rule.
 */
describe('ESLint custom rule ↔ test pairing invariant (phase 580)', () => {
  const repoRoot = path.join(__dirname, '..', '..', '..');
  const rulesDir = path.join(repoRoot, '.config', 'eslint-rules');
  const testsDir = path.join(repoRoot, 'tests', 'foundation', 'eslint-rules');

  it('every rule file has a matching test file (and no orphan tests)', () => {
    const ruleBasenames = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .map(f => f.slice(0, -3))
      .sort();
    const testBasenames = fs
      .readdirSync(testsDir)
      .filter(f => f.endsWith('.test.ts'))
      .map(f => f.slice(0, -8))
      .sort();

    const rulesMissingTests = ruleBasenames.filter(r => !testBasenames.includes(r));
    const testsMissingRules = testBasenames.filter(t => !ruleBasenames.includes(t));

    expect(rulesMissingTests).toEqual([]);
    expect(testsMissingRules).toEqual([]);
  });
});
});

describe('eslint-rule-test-run-name-matches-basename', () => {

/**
 * phase 606: invariant that every chestnut-custom rule test file's
 * `ruleTester.run('<name>', ...)` first argument matches the test file
 * basename (basename of `<name>.test.ts`).
 *
 * Rationale (ML#3 single-source naming): the RuleTester run name appears in
 * RuleTester failure output. Mismatched name → developer sees report text
 * naming the wrong rule, misdiagnoses scope (e.g. fail says 'no-foo' but
 * the test actually verifies 'no-bar' rule).
 *
 * Pairs with phase 580 (rule ↔ test 1:1), phase 587 (RuleTester usage),
 * phase 591 (3-way pairing), phase 605 (valid/invalid non-empty).
 */
describe('ESLint rule test ruleTester.run name === basename invariant (phase 606)', () => {
  it('every test file ruleTester.run() first arg matches basename', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const offenders: string[] = [];
    const runArgRe = /ruleTester\.run\(\s*['"]([^'"]+)['"]/;
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      const m = text.match(runArgRe);
      const basename = f.replace(/\.test\.ts$/, '');
      if (!m) {
        offenders.push(`${f}: no ruleTester.run('<name>', ...) found`);
        continue;
      }
      const runName = m[1];
      if (runName !== basename) {
        offenders.push(`${f}: runName='${runName}' !== basename='${basename}'`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-test-valid-invalid-non-empty', () => {

/**
 * phase 605: invariant that every chestnut-custom ESLint rule test file in
 * tests/foundation/eslint-rules/*.test.ts has non-empty `valid:` AND
 * `invalid:` arrays in its RuleTester invocation.
 *
 * Rationale: RuleTester requires both coverage sides:
 * - empty `valid:` → rule may over-fire on legitimate code, untested
 * - empty `invalid:` → rule may never trigger, broken-by-default passes
 *   silently (test pseudo-green / 测试伪绿)
 *
 * Both sides non-empty is the threshold for RuleTester to verify real
 * coverage. Pairs with phase 587 (RuleTester usage), phase 580 (rule ↔ test
 * 1:1), phase 585 (rule + test phase NNN).
 */
describe('ESLint rule test valid/invalid non-empty invariant (phase 605)', () => {
  it('every rule test file has non-empty valid AND invalid arrays', () => {
    const testDir = path.resolve(__dirname, '../../../tests/foundation/eslint-rules');
    const files = fs
      .readdirSync(testDir)
      .filter(f => f.endsWith('.test.ts'))
      .sort();

    const offenders: string[] = [];
    const emptyArrayRe = (key: string) => new RegExp(`${key}:\\s*\\[\\s*\\]`);
    for (const f of files) {
      const text = fs.readFileSync(path.join(testDir, f), 'utf-8');
      if (emptyArrayRe('valid').test(text)) offenders.push(`${f}: empty valid`);
      if (emptyArrayRe('invalid').test(text)) offenders.push(`${f}: empty invalid`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('eslint-rule-yingran-marker-invariant', () => {

/**
 * phase 598: invariant that every chestnut-custom ESLint rule under
 * .config/eslint-rules/*.js declares a 应然 (prescriptive principle) marker in
 * its file header (first 40 lines).
 *
 * Rationale: every chestnut-custom rule must trace back to a prescriptive
 * principle (M#5 单向, M#3 owner, M#7 边界, 编码规范, etc.). The 应然 marker
 * in the file header articulates *why* the rule exists — without it, the rule
 * decays into a descriptive ad-hoc grep with no anchor for future judgment
 * calls about scope, allowlist, or removal.
 *
 * Pairs with phase 597 (rule structural quartet), phase 596 (meta.type),
 * phase 593 (severity), phase 585 (phase reference in rule + test).
 */
describe('ESLint chestnut-custom rule 应然 marker invariant (phase 598)', () => {
  it('every .config/eslint-rules/*.js header (first 40 lines) contains 应然', () => {
    const rulesDir = path.resolve(__dirname, '../../../.config/eslint-rules');
    const files = fs
      .readdirSync(rulesDir)
      .filter(f => f.endsWith('.js'))
      .sort();

    const missing: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(rulesDir, f), 'utf-8');
      const header = text.split('\n').slice(0, 40).join('\n');
      if (!header.includes('应然')) missing.push(f);
    }
    expect(missing).toEqual([]);
  });
});
});

describe('forbidden-rule-comment-length-invariant', () => {

/**
 * phase 660: invariant that every depcruise forbidden rule's `comment`
 * field is at least 30 characters long.
 *
 * Rationale: comment is the SoT for the explanation users see at lint
 * failure. A trivial comment like `'forbidden'` or `'no'` leaves the
 * user knowing only the rule fired, not why or how to fix.
 *
 * Loose floor (30 chars) — current shortest is 108 chars; this catches
 * accidental copy-paste-trim that drops most of the comment, without
 * dictating long-form prose.
 *
 * phase 509 covers comment presence (non-null), phase 582 covers phase
 * NNN reference, phase 635 covers comment uniqueness. This phase adds
 * minimum-length guard (complementary).
 */
describe('depcruise rule comment length invariant (phase 660)', () => {
  it('every rule.comment.length ≥ 30', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{ name: string; comment?: string }>;
    };
    const offenders = cfg.forbidden
      .filter(r => (r.comment?.length ?? 0) < 30)
      .map(r => `${r.name} (len=${r.comment?.length ?? 0})`);
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-comment-unique-invariant', () => {

/**
 * phase 635: invariant that every depcruise forbidden rule has a unique
 * `comment` field — no two rules share the same comment string.
 *
 * Rationale (ML#3 single-source semantics): each rule's comment is the
 * SoT for that rule's *meaning*. Drift breaks invisibly when copy-paste
 * leaves two rules sharing a comment:
 * - rule A fires but the comment narrates rule B's intent → developer
 *   misdiagnoses scope
 * - delete rule A but its comment was the working SoT for rule B → B's
 *   intent doc lost
 *
 * Pairs with phase 559 (forbidden rule name uniqueness), phase 582
 * (comment phase reference), phase 633 (severity=error default).
 */
describe('depcruise forbidden rule comment uniqueness invariant (phase 635)', () => {
  it('every forbidden rule has unique comment', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{ name: string; comment?: string }>;
    };
    const seen = new Map<string, string>();
    const duplicates: string[] = [];
    for (const r of cfg.forbidden) {
      const c = r.comment ?? '';
      if (seen.has(c)) {
        duplicates.push(`${r.name} ↔ ${seen.get(c)} (shared comment: ${c.slice(0, 60)}…)`);
      } else {
        seen.set(c, r.name);
      }
    }
    expect(duplicates).toEqual([]);
  });
});
});

describe('forbidden-rule-from-path-invariant', () => {

/**
 * phase 595: invariant that every depcruise forbidden rule has a `from.path` or
 * `from.orphan` field defined (whitelisting `no-circular`, which is a
 * whole-graph cycle check without a from dimension).
 *
 * A rule without a `from` qualifier silently matches every source file in the
 * repo, producing false positives at scale or — depending on the `to`
 * configuration — silently matching nothing. Either failure mode masks intent.
 *
 * Pairs with phase 509 forbidden-rule-severity-invariant + phase 582
 * forbidden-rule-phase-reference + phase 579 forbidden-rule-naming-convention.
 */
describe('depcruise forbidden rule from.path|orphan invariant (phase 595)', () => {
  it('every forbidden rule has from.path or from.orphan (except no-circular)', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{
        name: string;
        from?: { path?: string | string[]; orphan?: boolean };
      }>;
    };
    const WHITELIST = new Set(['no-circular']);
    const missing: string[] = [];
    for (const r of cfg.forbidden) {
      if (WHITELIST.has(r.name)) continue;
      const hasPath = !!(r.from && r.from.path);
      const hasOrphan = !!(r.from && r.from.orphan);
      if (!hasPath && !hasOrphan) missing.push(r.name);
    }
    expect(missing).toEqual([]);
  });
});
});

describe('forbidden-rule-from-presence-invariant', () => {

/**
 * phase 678: invariant that every depcruise forbidden rule has a `from`
 * field present (even if it's an empty object {}).
 *
 * Rationale (ML#9 explicit pairing): rule's from + to is a source/target
 * pair; from must be explicit (even empty {}) for the rule to have
 * meaningful semantics. A rule with only `to` and no `from` is
 * un-interpretable — depcruise doesn't know where to start scanning.
 *
 * phase 595 covers from.path or from.orphan presence; phase 599 covers
 * to/orphan presence. This phase covers the `from` field itself being
 * present (complementary, defends a more basic invariant).
 *
 * Pairs with phase 595 (from.path|orphan presence), phase 599 (to or
 * orphan), phase 615 (options baseline).
 */
describe('depcruise forbidden rule from presence invariant (phase 678)', () => {
  it('every forbidden rule has from field defined', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{ name: string; from?: unknown }>;
    };
    const missing = cfg.forbidden
      .filter(r => r.from === undefined)
      .map(r => r.name);
    expect(missing).toEqual([]);
  });
});
});

describe('forbidden-rule-name-kebab-case-invariant', () => {

/**
 * phase 649: invariant that every depcruise forbidden rule name matches
 * strict kebab-case `/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/`.
 *
 * phase 579 covers prefix convention (must start with `no-` or contain
 * `-only-`) but doesn't enforce strict kebab-case format — e.g.,
 * `no-BadName` passes 579 but contains camelCase.
 *
 * Mirrors phase 648 (ESLint custom rule filename kebab-case) for the
 * depcruise rule-name surface. Pairs with phase 579 (prefix), phase
 * 559 (name uniqueness), phase 635 (comment uniqueness).
 */
describe('depcruise forbidden rule name kebab-case invariant (phase 649)', () => {
  it('every rule.name matches /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as { forbidden: Array<{ name: string }> };
    const kebab = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
    const offenders = cfg.forbidden
      .filter(r => !kebab.test(r.name))
      .map(r => r.name);
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-names-unique', () => {

/**
 * phase 510: invariant that all forbidden rule names are unique.
 *
 * dependency-cruiser would silently override rules with the same name,
 * so duplicate names lead to unexpected behavior. This catches it.
 */
describe('forbidden rule names uniqueness (phase 510)', () => {
  it('all forbidden rule names are unique', () => {
    const names = (config.forbidden as { name: string }[]).map(r => r.name);
    const dupes: string[] = [];
    const seen = new Set<string>();
    for (const n of names) {
      if (seen.has(n)) dupes.push(n);
      seen.add(n);
    }
    expect(dupes).toEqual([]);
  });
});
});

describe('forbidden-rule-naming-convention', () => {

/**
 * phase 579: invariant test that every forbidden rule name follows one of two
 * established conventions:
 *
 * 1. `no-<X>` prefix — forbid-direction / dead-pattern rules (49 条 baseline)
 *    e.g. no-core-to-assembly / no-circular / no-deep-into-*
 *
 * 2. `<resource>-only-from-<owner>` infix — resource唯一 owner rules (5 条 baseline)
 *    e.g. fs-only-via-foundation-filesystem / crypto-only-from-foundation /
 *         child-process-only-from-foundation-process-exec / net-only-from-foundation-transport
 *    (`fs-only-via-` 兼容 historical naming with `via` instead of `from`)
 *
 * Prevents naming-style drift when future rules are added.
 */
describe('forbidden rule naming convention invariant (phase 579)', () => {
  it('every forbidden rule name starts with "no-" or contains "-only-"', () => {
    const names = (config.forbidden as { name: string }[]).map(r => r.name);
    const violators = names.filter(n => !n.startsWith('no-') && !n.includes('-only-'));
    expect(violators).toEqual([]);
  });
});
});

describe('forbidden-rule-path-anchored-invariant', () => {

/**
 * phase 652: invariant that every depcruise forbidden rule's path regex
 * (`from.path`, `to.path`, supporting string or string[]) is anchored at
 * the start with `^`.
 *
 * Rationale (ML#3 accuracy + intent): without `^` the regex matches
 * anywhere in the file path. e.g., `src/foo` as `from.path` also matches
 * `node_modules/whatever/src/foo` — producing false positives that mask
 * the rule's intent + spam logs.
 *
 * Pairs with phase 638 (regex compile validity), phase 595 (from.path
 * presence), phase 599 (to/orphan presence), phase 649 (rule name
 * kebab-case).
 */
describe('depcruise forbidden rule path anchored invariant (phase 652)', () => {
  it('every from.path / to.path string starts with ^', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{
        name: string;
        from?: { path?: string | string[] };
        to?: { path?: string | string[] };
      }>;
    };
    const offenders: string[] = [];
    const check = (field: string, ruleName: string, value: unknown) => {
      if (typeof value === 'string') {
        if (!value.startsWith('^')) {
          offenders.push(`${ruleName}.${field}: ${value}`);
        }
      } else if (Array.isArray(value)) {
        for (const v of value) check(field, ruleName, v);
      }
    };
    for (const r of cfg.forbidden) {
      check('from.path', r.name, r.from?.path);
      check('to.path', r.name, r.to?.path);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-pathnot-anchored-invariant', () => {

/**
 * phase 653: invariant that every depcruise forbidden rule's
 * `from.pathNot` (allowlist exclusion regex) is anchored at either the
 * start (`^`) or end (`$`).
 *
 * phase 652 covered from.path/to.path requiring start anchor (`^`).
 * pathNot has a different semantic — it can legitimately anchor at the
 * end (e.g. `\.d\.ts$` excludes files ending in `.d.ts`). But it MUST
 * anchor at one end; an unanchored pathNot like `index.ts` would match
 * `node_modules/foo/index.ts` and `src/index.ts` indiscriminately,
 * making the allowlist range explode.
 *
 * Pairs with phase 652 (from.path/to.path start-anchored), phase 638
 * (regex compile validity), phase 595 (from.path presence).
 */
describe('depcruise forbidden rule pathNot anchored invariant (phase 653)', () => {
  it('every from.pathNot string starts with ^ OR ends with $', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{
        name: string;
        from?: { pathNot?: string | string[] };
      }>;
    };
    const offenders: string[] = [];
    const check = (ruleName: string, value: unknown) => {
      if (typeof value === 'string') {
        if (!value.startsWith('^') && !value.endsWith('$')) {
          offenders.push(`${ruleName}.from.pathNot: ${value}`);
        }
      } else if (Array.isArray(value)) {
        for (const v of value) check(ruleName, v);
      }
    };
    for (const r of cfg.forbidden) {
      check(r.name, r.from?.pathNot);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-pathnot-non-empty-invariant', () => {

/**
 * phase 677: invariant that depcruise forbidden rule's `from.pathNot`
 * (allowlist exclusion), when present, is non-empty.
 *
 * Rationale (ML#3 accuracy): pathNot is the allowlist exclusion. An
 * empty pathNot ([]) means "no allowlist" — same as not setting pathNot
 * at all. But explicit `pathNot: []` reads as intentional whereas
 * missing pathNot reads as default. Drift to empty array hides intent
 * and breaks future maintenance ("why is this empty?").
 *
 * Pairs with phase 653 (pathNot anchored), phase 638 (regex compile
 * validity), phase 595 (from.path presence), phase 652 (path anchored).
 */
describe('depcruise forbidden rule pathNot non-empty invariant (phase 677)', () => {
  it('every from.pathNot (if present) is non-empty', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{
        name: string;
        from?: { pathNot?: string | string[] };
      }>;
    };
    const offenders: string[] = [];
    for (const r of cfg.forbidden) {
      const pathNot = r.from?.pathNot;
      if (pathNot === undefined) continue;
      if (typeof pathNot === 'string') {
        if (pathNot.length === 0) offenders.push(`${r.name}: pathNot is empty string`);
      } else if (Array.isArray(pathNot)) {
        if (pathNot.length === 0) offenders.push(`${r.name}: pathNot is empty array`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-regex-valid-invariant', () => {

/**
 * phase 638: invariant that every depcruise forbidden rule's regex
 * fields (`from.path`, `from.pathNot`, `to.path`, `to.pathNot`) compile
 * cleanly as JS `RegExp`.
 *
 * Rationale (ML#9 explicit coupling): depcruise config regex strings are
 * passed to the JS RegExp engine. Drift breaks invisibly:
 * - missing escape (e.g. `(` not closed, `\` not doubled) → depcruise
 *   throws "Invalid regular expression" at config load
 * - pnpm lint:arch then fails with cryptic stack; root cause buried in
 *   config dump
 *
 * Catches the failure mode locally + fast — before pushing the broken
 * config to CI / running depcruise.
 *
 * Pairs with phase 595 (from.path|orphan), phase 599 (to/orphan), phase
 * 635 (comment uniqueness).
 */
describe('depcruise forbidden rule regex validity invariant (phase 638)', () => {
  it('every from.path/pathNot + to.path/pathNot string compiles as RegExp', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{
        name: string;
        from?: { path?: string | string[]; pathNot?: string | string[] };
        to?: { path?: string | string[]; pathNot?: string | string[] };
      }>;
    };
    const offenders: string[] = [];
    const tryCompile = (field: string, ruleName: string, value: unknown) => {
      if (typeof value === 'string') {
        try {
          new RegExp(value);
        } catch (e) {
          offenders.push(`${ruleName}.${field}: ${(e as Error).message}`);
        }
      } else if (Array.isArray(value)) {
        for (const v of value) tryCompile(field, ruleName, v);
      }
    };
    for (const r of cfg.forbidden) {
      tryCompile('from.path', r.name, r.from?.path);
      tryCompile('from.pathNot', r.name, r.from?.pathNot);
      tryCompile('to.path', r.name, r.to?.path);
      tryCompile('to.pathNot', r.name, r.to?.pathNot);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-severity-error-default-invariant', () => {

/**
 * phase 633: invariant that every depcruise forbidden rule's severity is
 * 'error', except for the explicit `WARN_WHITELIST` (currently just
 * `no-orphans`).
 *
 * Rationale (ML#3 fail-loud baseline): architectural invariants must
 * fail-loud (severity='error'). `warn` is reserved for the orphan-detection
 * case (high false-positive rate during refactors) and must be whitelisted
 * explicitly.
 *
 * Refines phase 509 (severity ∈ {error, warn} — coarse): this phase makes
 * the default = 'error' and forces every 'warn' to be deliberate and
 * recorded in the whitelist.
 *
 * Pairs with phase 595 (from.path), phase 599 (to/orphan), phase 615
 * (options baseline), phase 633 ratchet for forbidden rule severity.
 */
describe('depcruise forbidden rule severity=error default invariant (phase 633)', () => {
  it('every rule severity === "error" except WARN_WHITELIST', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{ name: string; severity: string }>;
    };
    const WARN_WHITELIST = new Set(['no-orphans']);
    const offenders: string[] = [];
    for (const r of cfg.forbidden) {
      if (WARN_WHITELIST.has(r.name)) {
        if (r.severity !== 'warn') {
          offenders.push(`${r.name}: whitelist expects 'warn', got '${r.severity}'`);
        }
      } else {
        if (r.severity !== 'error') {
          offenders.push(`${r.name}: severity='${r.severity}' (expected 'error')`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('forbidden-rule-severity-invariant', () => {

/**
 * phase 509: invariant that every forbidden rule has severity ∈ {error, warn}.
 *
 * Prevents accidental severity downgrade to info / off / undefined
 * which would silently disable enforcement.
 */
describe('forbidden rule severity invariant (phase 509)', () => {
  it('every forbidden rule has severity error or warn', () => {
    const allowed = new Set(['error', 'warn']);
    const bad = (config.forbidden as { name: string; severity: string }[])
      .filter(r => !allowed.has(r.severity))
      .map(r => `${r.name} (severity=${r.severity})`);
    expect(bad).toEqual([]);
  });

  it('every forbidden rule has a name and a comment', () => {
    const malformed = (config.forbidden as { name: string; comment?: string }[])
      .filter(r => !r.name || !r.comment)
      .map(r => r.name ?? '(unnamed)');
    expect(malformed).toEqual([]);
  });
});
});

describe('forbidden-rule-to-or-orphan-invariant', () => {

/**
 * phase 599: invariant that every depcruise forbidden rule has a target
 * dimension defined: `to.path`, `to.dependencyTypes`, `to.circular === true`,
 * or pairs with `from.orphan === true` (orphan check uses from.orphan + empty
 * to).
 *
 * Rationale: a forbidden rule without a target dimension has no meaningful
 * match — it either silently matches nothing or silently matches everything,
 * depending on the depcruise version. Both failure modes mask intent and
 * decay rule efficacy as the codebase grows.
 *
 * Pairs with phase 595 (from.path|orphan invariant — source dimension), phase
 * 582 (phase reference), phase 579 (naming convention), phase 509 (severity).
 */
describe('depcruise forbidden rule to/orphan invariant (phase 599)', () => {
  it('every forbidden rule has to.path, to.dependencyTypes, to.circular, or from.orphan', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{
        name: string;
        from?: { orphan?: boolean };
        to?: {
          path?: string | string[];
          dependencyTypes?: string[];
          circular?: boolean;
        };
      }>;
    };
    const missing: string[] = [];
    for (const r of cfg.forbidden) {
      const hasToPath = !!(r.to && r.to.path);
      const hasToDepTypes = !!(r.to && r.to.dependencyTypes);
      const hasToCircular = r.to?.circular === true;
      const hasFromOrphan = r.from?.orphan === true;
      if (!hasToPath && !hasToDepTypes && !hasToCircular && !hasFromOrphan) {
        missing.push(r.name);
      }
    }
    expect(missing).toEqual([]);
  });
});
});

describe('forbidden-rule-to-presence-invariant', () => {

/**
 * phase 679: invariant that every depcruise forbidden rule has a `to`
 * field present (even if it's an empty object {}).
 *
 * Mirrors phase 678 (from field presence) to the `to` side. Rule
 * from + to is a source/target pair; both must be explicit (even
 * empty {}) for the rule to be interpretable.
 *
 * Pairs with phase 678 (from presence), phase 599 (to.path|circular|
 * dep|from.orphan content), phase 595 (from.path|orphan content).
 */
describe('depcruise forbidden rule to presence invariant (phase 679)', () => {
  it('every forbidden rule has to field defined', () => {
    const cfgPath = path.resolve(__dirname, '../../../.config/dependency-cruiser.cjs');
    const cfg = require(cfgPath) as {
      forbidden: Array<{ name: string; to?: unknown }>;
    };
    const missing = cfg.forbidden
      .filter(r => r.to === undefined)
      .map(r => r.name);
    expect(missing).toEqual([]);
  });
});
});

describe('test-file-kebab-case-invariant', () => {

/**
 * phase 650: invariant that every test file under tests/foundation/arch/
 * and tests/foundation/eslint-rules/ has a basename (without .test.ts) in
 * strict kebab-case `/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/`.
 *
 * Rationale (ML#3 single-source naming): test files mirror their src
 * surface (config rule files / depcruise rule names) which are themselves
 * kebab-case. Drift to camelCase / snake_case fragments grep, IDE
 * navigation, and breaks the basename-as-key pattern used by phase 580
 * rule ↔ test pairing.
 *
 * Extends phase 648 (ESLint rule filename kebab-case) + phase 649
 * (depcruise rule name kebab-case) to the test-file layer.
 */
const KEBAB = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

describe('arch + eslint-rules test file kebab-case invariant (phase 650)', () => {
  it('every test file basename matches kebab-case', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const dirs = [
      'tests/foundation/arch',
      'tests/foundation/eslint-rules',
    ];
    const offenders: string[] = [];
    for (const d of dirs) {
      const dirPath = path.join(repoRoot, d);
      const files = fs.readdirSync(dirPath).filter(f => f.endsWith('.test.ts'));
      for (const f of files) {
        const rawBasename = f.replace(/\.test\.ts$/, '');
        // Phase 1008 merged invariants use `<topic>.invariant.test.ts`; validate the kebab-case prefix.
        const basename = rawBasename.endsWith('.invariant')
          ? rawBasename.slice(0, -'.invariant'.length)
          : rawBasename;
        if (!KEBAB.test(basename)) offenders.push(`${d}/${f}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

