import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * phase 613: invariant that every package.json entry path (main / module /
 * bin / exports['.']) maps to a tsup config entry with the matching format
 * (esm → .js, cjs → .cjs).
 *
 * Rationale (ML#9 explicit coupling): package.json entry paths and tsup
 * build entries are an inescapable coupling. Drift breaks invisibly until
 * publish:
 * - tsup drops `cli` entry but package.json keeps `bin.chestnut` →
 *   `npm install` succeeds, `chestnut` command fails with ENOENT.
 * - tsup renames entry → package.json stays on old name → same break.
 *
 * Extends phase 612 (path shape) with build-config target verification.
 *
 * Skips `types` field (auto-generated by `dts: true` from the library
 * build entry).
 */
type TsupEntry = { entry: Record<string, string>; format: string[] };

describe('package.json ↔ tsup entry pairing invariant (phase 613)', () => {
  it('every package entry path maps to a tsup entry with matching format', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const pkgPath = path.join(repoRoot, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      main?: string;
      module?: string;
      bin?: Record<string, string>;
      exports?: Record<string, Record<string, string>>;
    };

    const tsupCfgPath = path.join(repoRoot, '.config/tsup.config.ts');
    const mod = (await import(tsupCfgPath)) as { default?: unknown };
    const raw = mod.default;
    // tsup defineConfig returns an array (or a function) — here it's an array.
    const tsupEntries: TsupEntry[] = Array.isArray(raw) ? (raw as TsupEntry[]) : [];
    expect(tsupEntries.length).toBeGreaterThan(0);

    // Build a set of (entryName, format) tuples produced by tsup.
    const produced = new Set<string>();
    for (const seg of tsupEntries) {
      for (const name of Object.keys(seg.entry ?? {})) {
        for (const fmt of seg.format ?? []) produced.add(`${name}:${fmt}`);
      }
    }

    const pkgPaths: Array<{ label: string; value: string | undefined }> = [
      { label: 'main', value: pkg.main },
      { label: 'module', value: pkg.module },
      { label: 'bin.chestnut', value: pkg.bin?.chestnut },
      { label: 'exports["."].import', value: pkg.exports?.['.']?.import },
      { label: 'exports["."].require', value: pkg.exports?.['.']?.require },
    ];

    const offenders: string[] = [];
    for (const { label, value } of pkgPaths) {
      if (typeof value !== 'string') {
        offenders.push(`${label}: not a string`);
        continue;
      }
      const m = value.match(/^\.\/dist\/([^/]+)\.(js|cjs)$/);
      if (!m) {
        offenders.push(`${label}=${value}: doesn't match ./dist/<name>.{js|cjs}`);
        continue;
      }
      const [, name, ext] = m;
      const fmt = ext === 'cjs' ? 'cjs' : 'esm';
      if (!produced.has(`${name}:${fmt}`)) {
        offenders.push(`${label}=${value}: tsup has no (${name}, ${fmt}) entry`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
