// Auto-generated by Phase 1008 Step C: merged arch invariant tests.
// Do not edit manually; edit the original per-topic tests instead.

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

describe('ci-node-version-engines-invariant', () => {

/**
 * phase 627: invariant that every `node-version:` in CI workflows has a
 * major version ≥ the major version in package.json `engines.node`.
 *
 * Rationale (ML#9 explicit coupling): engines.node + CI node-version must
 * satisfy a containment relation — CI versions ⊆ engines-allowed range.
 * Drift breaks invisibly:
 * - engines.node bumped to '>=24' but CI keeps testing 22.x → CI passes
 *   on unsupported version; users on 24+ may hit untested failures
 * - CI adds 18.x to matrix but engines.node still '>=20.18.0' → CI runs
 *   unsupported version; passes mean nothing for engines-compliant users
 *
 * The invariant doesn't lock a specific major (project may upgrade either
 * side independently as long as the containment holds).
 *
 * Pairs with phase 626 (pnpm version consistency), phase 625 (action
 * pinning), phase 621 (package identity).
 */
describe('CI node-version vs engines.node invariant (phase 627)', () => {
  it('every CI node-version major >= engines.node minMajor', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const pkgPath = path.join(repoRoot, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      engines?: { node?: string };
    };
    const enginesNode = pkg.engines?.node;
    expect(typeof enginesNode).toBe('string');
    const minMatch = (enginesNode as string).match(/^>=(\d+)/);
    expect(minMatch).not.toBeNull();
    const minMajor = parseInt(minMatch![1], 10);

    const wfDir = path.join(repoRoot, '.github/workflows');
    const files = fs.readdirSync(wfDir).filter(f => f.endsWith('.yml')).sort();
    expect(files.length).toBeGreaterThan(0);

    // matches `node-version: <value>` lines (with optional quotes/array brackets)
    const lineRe = /node-version:\s+(\S+(?:\s*,\s*\S+)*)/g;
    const versionRe = /(\d+)\.[\d.xX]+/g;
    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(wfDir, f), 'utf-8');
      let lm: RegExpExecArray | null;
      while ((lm = lineRe.exec(text)) !== null) {
        // Skip `${{ matrix.node-version }}` substitutions — already resolved
        // by the matrix line.
        const val = lm[1];
        if (val.includes('${{')) continue;
        let vm: RegExpExecArray | null;
        while ((vm = versionRe.exec(val)) !== null) {
          const major = parseInt(vm[1], 10);
          if (major < minMajor) {
            offenders.push(`${f}: node-version ${vm[0]} major=${major} < minMajor=${minMajor}`);
          }
        }
        versionRe.lastIndex = 0;
      }
      lineRe.lastIndex = 0;
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('ci-workflow-action-version-pinning-invariant', () => {

/**
 * phase 625: invariant that every GitHub Actions `uses:` reference in
 * .github/workflows/*.yml is version-pinned to `@vN[.M[.P]]` or a 40-char
 * commit SHA. Bans `@main`, `@master`, `@latest`, and unversioned refs.
 *
 * Rationale (ML#3 single-source + security baseline):
 * - `@main` / `@master` → action author's push to main immediately changes
 *   what CI runs; can introduce breaking changes or — worse — silent
 *   security regression if the action publisher is compromised.
 * - `@latest` → similar non-reproducibility.
 * - unversioned (just `owner/repo`) → GitHub default behavior is
 *   action-specific, generally unpredictable.
 *
 * Pins to `@vN` (or SHA) provide reproducibility + bounded blast radius.
 * Lock at this level (allow any version), not a specific version (allow
 * the project to upgrade without changing this invariant).
 *
 * Pairs with phase 624 (post-merge hook), phase 623 (CI script ref),
 * phase 622 (.gitignore baseline).
 */
describe('CI workflow action version pinning invariant (phase 625)', () => {
  it('every uses: ref pins @vN or @<40-hex-sha>', () => {
    const wfDir = path.resolve(__dirname, '../../../.github/workflows');
    const files = fs.readdirSync(wfDir).filter(f => f.endsWith('.yml')).sort();
    expect(files.length).toBeGreaterThan(0);

    const usesRe = /uses:\s+([\w.-]+\/[\w.-]+)@(\S+)/g;
    const semverOrV = /^v?\d+(\.\d+){0,2}$/;
    const sha40 = /^[a-f0-9]{40}$/;
    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(wfDir, f), 'utf-8');
      let m: RegExpExecArray | null;
      while ((m = usesRe.exec(text)) !== null) {
        const repo = m[1];
        const ref = m[2];
        if (!semverOrV.test(ref) && !sha40.test(ref)) {
          offenders.push(`${f}: ${repo}@${ref}`);
        }
      }
      usesRe.lastIndex = 0;
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('ci-workflow-pnpm-install-frozen-invariant', () => {

/**
 * phase 642: invariant that every `pnpm install` invocation in
 * .github/workflows/*.yml includes the `--frozen-lockfile` flag.
 *
 * Rationale (ML#3 reproducibility baseline): CI must bind to the
 * lockfile (frozen). Without --frozen-lockfile pnpm may re-resolve when
 * the lockfile is out of sync with package.json, masking lockfile drift
 * and shipping different versions to CI than to dev environments.
 *
 * Pairs with phase 641 (trigger symmetry), phase 626 (pnpm version
 * consistency), phase 627 (node version vs engines), phase 623 (script
 * ref).
 */
describe('CI workflow pnpm install --frozen-lockfile invariant (phase 642)', () => {
  it('every pnpm install in workflows uses --frozen-lockfile', () => {
    const wfDir = path.resolve(__dirname, '../../../.github/workflows');
    const files = fs.readdirSync(wfDir).filter(f => f.endsWith('.yml')).sort();
    expect(files.length).toBeGreaterThan(0);

    const offenders: string[] = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(wfDir, f), 'utf-8');
      for (const line of text.split('\n')) {
        // Match `pnpm install` but not `pnpm install-test` etc.
        if (/\bpnpm install\b/.test(line)) {
          if (!line.includes('--frozen-lockfile')) {
            offenders.push(`${f}: ${line.trim()}`);
          }
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('ci-workflow-pnpm-script-ref-invariant', () => {

/**
 * phase 623: invariant that every `pnpm run <script>` invocation in
 * .github/workflows/*.yml references a script defined in package.json.
 *
 * Rationale (ML#9 explicit coupling): workflow yml literals + package.json
 * scripts are an inescapable coupling. Drift breaks invisibly:
 * - rename script (lint:lint → lint:eslint) but forget workflow → CI
 *   fails on push with "Missing script: lint:lint"; sometimes only caught
 *   on push to main (not PR if PR didn't trigger that workflow).
 * - delete script but workflow still calls → same break.
 *
 * One-way: workflow → package.json (workflow ref must exist). Reverse
 * direction (package.json script → workflow) is intentionally NOT
 * enforced; not every dev script needs CI.
 *
 * Pairs with phase 622 (.gitignore baseline), phase 621 (package
 * identity), phase 600/602 (script config SoT).
 */
describe('CI workflow pnpm script ref invariant (phase 623)', () => {
  it('every pnpm run <script> in .github/workflows references a defined script', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const pkgPath = path.join(repoRoot, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      scripts: Record<string, string>;
    };
    const scriptNames = new Set(Object.keys(pkg.scripts));

    const wfDir = path.join(repoRoot, '.github/workflows');
    const wfFiles = fs.readdirSync(wfDir).filter(f => f.endsWith('.yml')).sort();
    expect(wfFiles.length).toBeGreaterThan(0);

    const pnpmRunRe = /pnpm run ([a-zA-Z:][a-zA-Z0-9:_-]*)/g;
    const offenders: string[] = [];
    for (const f of wfFiles) {
      const text = fs.readFileSync(path.join(wfDir, f), 'utf-8');
      let m: RegExpExecArray | null;
      while ((m = pnpmRunRe.exec(text)) !== null) {
        const ref = m[1];
        if (!scriptNames.has(ref)) {
          offenders.push(`${f}: pnpm run ${ref} (not in package.json scripts)`);
        }
      }
      pnpmRunRe.lastIndex = 0;
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('ci-workflow-pnpm-version-consistency-invariant', () => {

/**
 * phase 626: invariant that every `pnpm/action-setup` block in
 * .github/workflows/*.yml uses the same `version: N` value.
 *
 * Rationale (ML#3 single-source toolchain): pnpm version is part of the
 * build toolchain — must be uniform across CI. Drift breaks invisibly:
 * - one CI runs pnpm v10 to parse lockfile, another v11 → same PR exhibits
 *   different behavior (one passes, one fails) for the same source
 * - debugging CI failures becomes unrepeatable (depends which workflow ran)
 *
 * Doesn't lock a specific version — only that all workflows agree.
 * Project can upgrade by editing all 3 in one commit; this invariant
 * stops the half-finished upgrade.
 *
 * Matches the YAML pattern:
 *   uses: pnpm/action-setup@vN
 *     ...
 *     with:
 *       version: N
 *
 * Pairs with phase 625 (action version pinning), phase 624 (post-merge),
 * phase 623 (CI script ref).
 */
describe('CI workflow pnpm version consistency invariant (phase 626)', () => {
  it('every pnpm/action-setup invocation uses same version', () => {
    const wfDir = path.resolve(__dirname, '../../../.github/workflows');
    const files = fs.readdirSync(wfDir).filter(f => f.endsWith('.yml')).sort();
    expect(files.length).toBeGreaterThan(0);

    // Find each pnpm/action-setup block, then capture the next `version:` value.
    // YAML matters: under `with:` block of pnpm/action-setup.
    const blockRe = /uses:\s+pnpm\/action-setup@v\d+[\s\S]*?version:\s+(\S+)/g;
    const versions: Array<{ file: string; version: string }> = [];
    for (const f of files) {
      const text = fs.readFileSync(path.join(wfDir, f), 'utf-8');
      let m: RegExpExecArray | null;
      while ((m = blockRe.exec(text)) !== null) {
        versions.push({ file: f, version: m[1] });
      }
      blockRe.lastIndex = 0;
    }
    expect(versions.length).toBeGreaterThan(0);
    const uniqueVersions = new Set(versions.map(v => v.version));
    expect(uniqueVersions.size).toBe(1);
  });
});
});

describe('ci-workflow-runs-on-cache-invariant', () => {

/**
 * phase 643: invariant that every CI workflow has:
 * - `runs-on: ubuntu-latest` (consistent CI runner)
 * - `setup-node` with `cache: 'pnpm'` (consistent dependency caching)
 *
 * Rationale (ML#3 single-source CI platform + caching):
 * - runs-on drift to macos-latest → CI output not directly comparable to
 *   prod (which targets Linux), wall-time + cost increases
 * - cache drift (or missing) → every CI run reinstalls all deps from
 *   scratch, wall-time explodes
 *
 * Pairs with phase 642 (--frozen-lockfile), phase 641 (trigger symmetry),
 * phase 626 (pnpm version), phase 627 (node vs engines).
 */
describe('CI workflow runs-on + setup-node cache invariant (phase 643)', () => {
  it('every workflow uses ubuntu-latest + setup-node cache=pnpm', () => {
    const wfDir = path.resolve(__dirname, '../../../.github/workflows');
    const files = fs.readdirSync(wfDir).filter(f => f.endsWith('.yml')).sort();
    expect(files.length).toBeGreaterThan(0);

    const runsOnOffenders: string[] = [];
    const cacheOffenders: string[] = [];
    const runsOnRe = /runs-on:\s+(\S+)/g;
    const setupNodeCacheRe = /uses:\s+actions\/setup-node@v\d+[\s\S]*?cache:\s+['"]?([^'"\s]+)['"]?/g;

    for (const f of files) {
      const text = fs.readFileSync(path.join(wfDir, f), 'utf-8');
      let m: RegExpExecArray | null;
      while ((m = runsOnRe.exec(text)) !== null) {
        if (m[1] !== 'ubuntu-latest') {
          runsOnOffenders.push(`${f}: runs-on=${m[1]}`);
        }
      }
      runsOnRe.lastIndex = 0;
      while ((m = setupNodeCacheRe.exec(text)) !== null) {
        if (m[1] !== 'pnpm') {
          cacheOffenders.push(`${f}: setup-node cache=${m[1]}`);
        }
      }
      setupNodeCacheRe.lastIndex = 0;
    }
    expect(runsOnOffenders).toEqual([]);
    expect(cacheOffenders).toEqual([]);
  });
});
});

describe('ci-workflow-trigger-symmetry-invariant', () => {

/**
 * phase 641: invariant that ci.yml + code-quality.yml workflows share the
 * same trigger surface — both fire on `push.branches: [main]` AND
 * `pull_request.branches: [main]`.
 *
 * Rationale (ML#3 single-source CI symmetry): ci + code-quality are
 * sister workflows; they must cover the same set of events to avoid
 * asymmetric checks on the same PR. Drift breaks invisibly:
 * - add a branch to ci.yml push but forget code-quality → that branch
 *   gets type/test checks but not lint/arch
 * - drop pull_request from one → PRs against main get partial coverage
 *
 * release.yml has different semantics (tag push) and is intentionally
 * excluded.
 *
 * Pairs with phase 626 (pnpm version consistency), phase 627 (node
 * version vs engines), phase 623 (script ref).
 */
describe('CI workflow trigger symmetry invariant (phase 641)', () => {
  it('ci.yml + code-quality.yml both fire on push + pull_request to main', () => {
    const wfDir = path.resolve(__dirname, '../../../.github/workflows');
    const sisters = ['ci.yml', 'code-quality.yml'];

    const offenders: string[] = [];
    for (const f of sisters) {
      const p = path.join(wfDir, f);
      expect(fs.existsSync(p), `${f} missing`).toBe(true);
      const text = fs.readFileSync(p, 'utf-8');
      // crude but adequate string checks — YAML is line-based
      if (!/push:\s*\n\s*branches:\s*\[\s*main\s*\]/m.test(text)) {
        offenders.push(`${f}: missing push.branches: [main]`);
      }
      if (!/pull_request:\s*\n\s*branches:\s*\[\s*main\s*\]/m.test(text)) {
        offenders.push(`${f}: missing pull_request.branches: [main]`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('gitignore-baseline-invariant', () => {

/**
 * phase 622: invariant that .gitignore contains 6 baseline patterns
 * (each on its own line, exact-trim match):
 * - `node_modules`     — deps (100+ MB, never in repo)
 * - `dist/`            — build output (would create eternal-dirty state)
 * - `.chestnut/`       — runtime data (claw workspaces, agent state,
 *                        audit logs)
 * - `.env`             — secrets (must never enter version control)
 * - `coverage/`        — vitest --coverage output (transient)
 * - `.tsbuildinfo`     — TS incremental cache (drifts every build)
 *
 * Rationale: each missing entry has a distinct failure mode — repo bloat,
 * secret leak, eternal-dirty status, etc. The 6 are not optional
 * optimizations; they're security + hygiene baselines.
 *
 * Phase 622 doesn't lock the full .gitignore content (OS-specific lines
 * like .DS_Store, IDE lines like .vscode/ remain elastic). Only the 6
 * required baselines.
 *
 * Pairs with phase 621 (package identity), phase 612 (entry points).
 */
describe('.gitignore baseline patterns invariant (phase 622)', () => {
  it('contains 6 baseline patterns', () => {
    const gitignorePath = path.resolve(__dirname, '../../../.gitignore');
    const text = fs.readFileSync(gitignorePath, 'utf-8');
    const lines = text.split('\n').map(l => l.trim());
    const REQUIRED = [
      'node_modules',
      'dist/',
      '.chestnut/',
      '.env',
      'coverage/',
      '.tsbuildinfo',
    ];
    const missing = REQUIRED.filter(pat => !lines.includes(pat));
    expect(missing).toEqual([]);
  });
});
});

describe('package-json-entry-points-invariant', () => {

/**
 * phase 612: invariant that package.json entry points all reference
 * `./dist/*` build outputs (not source-tree paths) and `type === 'module'`.
 *
 * Rationale (ML#3 single-source publishing):
 * - main / module / types / bin / exports['.'] are the distribution surface.
 *   A path pointing at `./src/*` after npm publish would mean users install
 *   a package that imports TS source they can't run.
 * - `type: 'module'` decides .js parse mode. Drift to 'commonjs' flips every
 *   ESM import → require, breaking ESM-only deps.
 *
 * Pairs with phase 611 (vitest exclude base), phase 610 (project names),
 * phase 608 (tsconfig strict).
 */
describe('package.json entry points invariant (phase 612)', () => {
  it('type=module + all dist-prefixed entry paths', () => {
    const pkgPath = path.resolve(__dirname, '../../../package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      type?: unknown;
      main?: unknown;
      module?: unknown;
      types?: unknown;
      bin?: Record<string, unknown>;
      exports?: Record<string, Record<string, unknown>>;
    };

    expect(pkg.type).toBe('module');

    const entries: Array<{ name: string; value: unknown }> = [
      { name: 'main', value: pkg.main },
      { name: 'module', value: pkg.module },
      { name: 'types', value: pkg.types },
      { name: 'bin.chestnut', value: pkg.bin?.chestnut },
      { name: 'exports["."].import', value: pkg.exports?.['.']?.import },
      { name: 'exports["."].require', value: pkg.exports?.['.']?.require },
    ];

    const offenders: string[] = [];
    for (const { name, value } of entries) {
      if (typeof value !== 'string' || !value.startsWith('./dist/')) {
        offenders.push(`${name}=${String(value)}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('package-json-identity-invariant', () => {

/**
 * phase 621: invariant that package.json publish identity fields are at
 * baseline:
 * - name === 'chestnut'
 * - license === 'MIT'
 * - engines.node startsWith '>=20'
 * - keywords is non-empty array
 *
 * Rationale (ML#3 single-source identity):
 * - name drift → npm publish ships under a different name; users of old
 *   name break + ecosystem fragmentation
 * - license drift → compliance / legal exposure
 * - engines.node drift below 20 → users on insufficient Node version see
 *   install succeed but runtime fail with cryptic error (npm warns but
 *   doesn't block)
 * - keywords empty → npm search invisible
 *
 * Excludes `version` (must change every release) and `description` (may
 * legitimately edit over time).
 *
 * Pairs with phase 612 (entry points), phase 613 (tsup pairing), phase
 * 620 (tsconfig build behavior).
 */
describe('package.json identity invariant (phase 621)', () => {
  it('name + license + engines.node + keywords match baseline', () => {
    const pkgPath = path.resolve(__dirname, '../../../package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      name?: unknown;
      license?: unknown;
      engines?: { node?: unknown };
      keywords?: unknown;
    };

    expect(pkg.name).toBe('chestnut');
    expect(pkg.license).toBe('MIT');
    const nodeRange = pkg.engines?.node;
    expect(typeof nodeRange).toBe('string');
    expect((nodeRange as string).startsWith('>=20')).toBe(true);
    expect(Array.isArray(pkg.keywords)).toBe(true);
    expect((pkg.keywords as unknown[]).length).toBeGreaterThan(0);
  });
});
});

describe('pnpm-lock-version-and-docs-invariant', () => {

/**
 * phase 640: invariant that:
 * - pnpm-lock.yaml declares `lockfileVersion: '9.0'` near the top
 *   (current pnpm 10 produces this; drift means lockfile format changed
 *   under us, possibly breaking CI install)
 * - README.md exists (project entry-point documentation)
 * - CONTRIBUTING.md exists (contribution process documentation)
 *
 * Rationale: pnpm-lock version is the SoT for dependency-resolution
 * format. Mismatch with installed pnpm major can cause CI install to
 * fail or silently re-resolve unintended versions. README/CONTRIBUTING
 * are project onboarding SoT — accidental deletion → users hit
 * documentation cliff.
 *
 * Extends phase 639 (LICENSE / pnpm-lock existence / .gitattributes) with
 * lockfile version content + onboarding doc presence.
 */
describe('pnpm-lock.yaml version + README/CONTRIBUTING invariant (phase 640)', () => {
  it('lockfile declares 9.0 + entry-point docs exist', () => {
    const repoRoot = path.resolve(__dirname, '../../..');

    const lockPath = path.join(repoRoot, 'pnpm-lock.yaml');
    expect(fs.existsSync(lockPath)).toBe(true);
    const lockHead = fs
      .readFileSync(lockPath, 'utf-8')
      .split('\n')
      .slice(0, 10)
      .join('\n');
    expect(lockHead).toContain("lockfileVersion: '9.0'");

    expect(fs.existsSync(path.join(repoRoot, 'README.md'))).toBe(true);
    expect(fs.existsSync(path.join(repoRoot, 'CONTRIBUTING.md'))).toBe(true);
  });
});
});

describe('post-merge-hook-invariant', () => {

/**
 * phase 624: invariant that .githooks/post-merge exists, is owner-executable,
 * runs `pnpm run typecheck` + `pnpm run test:run`, and both script names
 * are defined in package.json scripts.
 *
 * Rationale: post-merge hook is the final safety net — it runs after
 * `git merge` completes and verifies the merged tree before the user
 * proceeds. Drift breaks invisibly:
 * - file deleted → no post-merge verification, broken merges flow into
 *   main without local trip-wire
 * - executable bit lost → git silently skips the hook (no error reported)
 * - referenced script renamed in package.json → hook fails with "Missing
 *   script" but the merge is already recorded
 *
 * Extends phase 623 (CI workflow → package.json script ref) to the
 * git-hook channel.
 */
describe('post-merge hook invariant (phase 624)', () => {
  it('exists + executable + calls typecheck/test:run defined in package.json', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const hookPath = path.join(repoRoot, '.githooks/post-merge');
    expect(fs.existsSync(hookPath)).toBe(true);

    const st = fs.statSync(hookPath);
    expect(st.mode & 0o100).not.toBe(0); // owner-execute

    const text = fs.readFileSync(hookPath, 'utf-8');
    const required = ['pnpm run typecheck', 'pnpm run test:diff'];
    const missing = required.filter(r => !text.includes(r));
    expect(missing).toEqual([]);

    const pkgPath = path.join(repoRoot, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      scripts: Record<string, string>;
    };
    const scriptNames = new Set(Object.keys(pkg.scripts));
    expect(scriptNames.has('typecheck')).toBe(true);
    expect(scriptNames.has('test:run')).toBe(true);
  });
});
});

describe('release-workflow-tag-permissions-invariant', () => {

/**
 * phase 644: invariant that .github/workflows/release.yml:
 * - declares `on.push.tags: ['v*']` — release fires only on v-prefixed
 *   tag push (not arbitrary commits)
 * - declares `permissions: contents: write` — Github Actions defaults
 *   to read-only; softprops/action-gh-release needs write permission to
 *   create the release artifact
 *
 * Rationale (ML#3 single-source release surface + security baseline):
 * - tag pattern drift → release fires on unintended events (e.g.,
 *   accidental push to a branch named 'v-experiment')
 * - permissions drop → release step fails 403 "Resource not accessible
 *   by integration" on first attempt; only discovered when actually
 *   tagging a release
 *
 * Pairs with phase 643 (runs-on + cache), phase 642 (--frozen-lockfile),
 * phase 625 (action pinning), phase 641 (trigger symmetry — for
 * non-release workflows).
 */
describe('release.yml tag + permissions invariant (phase 644)', () => {
  it('triggers on v* tag push + permissions contents: write', () => {
    const releasePath = path.resolve(
      __dirname,
      '../../../.github/workflows/release.yml',
    );
    expect(fs.existsSync(releasePath)).toBe(true);
    const text = fs.readFileSync(releasePath, 'utf-8');

    // Tag pattern check: must match `tags:` then `- 'v*'` (yaml multi-line)
    expect(text).toMatch(/tags:\s*\n\s*-\s+['"]v\*['"]/);
    // Permission check: contents: write under permissions: block
    expect(text).toMatch(/permissions:\s*\n\s*contents:\s+write/);
  });
});
});

describe('repo-baseline-files-invariant', () => {

/**
 * phase 639: invariant that 3 repo baseline files exist + are well-formed:
 * - LICENSE              — MIT text (package.json declares license=MIT,
 *                          must be backed by an actual LICENSE file or
 *                          users have no legal certainty)
 * - pnpm-lock.yaml       — pnpm lockfile (CI runs `pnpm install
 *                          --frozen-lockfile`; missing → CI installs
 *                          latest versions → non-reproducible)
 * - .gitattributes       — must contain `.config/dependency-cruiser.cjs
 *                          merge=union` line (multi-branch adds to
 *                          dependency-cruiser.cjs rely on union merge to
 *                          avoid manual conflict resolution)
 *
 * Rationale: each missing file has a distinct failure mode — license
 * ambiguity, non-reproducible CI, merge conflict storms during parallel
 * rule additions. Security/hygiene baselines, not optional optimizations.
 *
 * Pairs with phase 622 (.gitignore baseline), phase 621 (package
 * identity), phase 626 (CI pnpm version consistency).
 */
describe('repo baseline files invariant (phase 639)', () => {
  it('LICENSE + pnpm-lock.yaml exist + .gitattributes has dependency-cruiser union merge', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    expect(fs.existsSync(path.join(repoRoot, 'LICENSE'))).toBe(true);
    expect(fs.existsSync(path.join(repoRoot, 'pnpm-lock.yaml'))).toBe(true);

    const gitattributesPath = path.join(repoRoot, '.gitattributes');
    expect(fs.existsSync(gitattributesPath)).toBe(true);
    const text = fs.readFileSync(gitattributesPath, 'utf-8');
    expect(text).toContain('.config/dependency-cruiser.cjs merge=union');
  });
});
});

describe('script-tool-config-sot-invariant', () => {

/**
 * phase 602: invariant that every package.json script invoking vitest /
 * depcruise / eslint / tsup references the corresponding config file under
 * `.config/`.
 *
 * Rationale (ML#3 single-source ownership): each tool's config SoT lives at
 * `.config/`, not repo root. A script that invokes a tool without the
 * explicit `--config` flag falls back to the tool's default config resolution
 * (which searches repo root), creating a silent split between two configs
 * that drift independently.
 *
 * Extends phase 600 (test* scripts → vitest config) to all four tools.
 */
const TOOL_CONFIG_PAIRS: Array<{ tool: string; config: string }> = [
  { tool: 'vitest', config: '.config/vitest.config.ts' },
  { tool: 'depcruise', config: '.config/dependency-cruiser.cjs' },
  { tool: 'eslint', config: '.config/eslint.config.js' },
  { tool: 'tsup', config: '.config/tsup.config.ts' },
];

describe('package.json tool config SoT invariant (phase 602)', () => {
  it('every script invoking a known tool references --config .config/<config>', () => {
    const pkgPath = path.resolve(__dirname, '../../../package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      scripts: Record<string, string>;
    };

    const offenders: string[] = [];
    for (const [name, value] of Object.entries(pkg.scripts)) {
      for (const { tool, config } of TOOL_CONFIG_PAIRS) {
        const toolPattern = new RegExp(`(^|[\\s&|])${tool}(\\s|$)`);
        if (!toolPattern.test(value)) continue;
        if (!value.includes(`--config ${config}`)) {
          offenders.push(`${name}: invokes ${tool} without --config ${config}`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('test-script-vitest-config-sot-invariant', () => {

/**
 * phase 600: invariant that every package.json script whose name starts with
 * `test` references `--config .config/vitest.config.ts`.
 *
 * Rationale (ML#3 single-source ownership): the vitest configuration SoT
 * lives at `.config/vitest.config.ts`, not at repo root. Any test script
 * missing the explicit `--config` flag falls back to vitest's default config
 * resolution (which searches for `vitest.config.ts` / `vite.config.ts` at
 * repo root), creating a silent split between two configs that drift
 * independently.
 *
 * Pairs with phase 597 (ESLint rule structural completeness), phase 595
 * (forbidden rule from.path), phase 580 (rule ↔ test pairing).
 */
describe('package.json test* script vitest.config.ts SoT invariant (phase 600)', () => {
  it('every script named test* references --config .config/vitest.config.ts', () => {
    const pkgPath = path.resolve(__dirname, '../../../package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      scripts: Record<string, string>;
    };

    const testScripts = Object.entries(pkg.scripts).filter(([name]) =>
      name.startsWith('test'),
    );

    expect(testScripts.length).toBeGreaterThan(0);

    const missing: string[] = [];
    for (const [name, value] of testScripts) {
      if (!value.includes('--config .config/vitest.config.ts')) {
        missing.push(`${name}: ${value}`);
      }
    }
    expect(missing).toEqual([]);
  });
});
});

