// Auto-generated by Phase 1008 Step C: merged arch invariant tests.
// Do not edit manually; edit the original per-topic tests instead.

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

describe('config-imports-deps-invariant', () => {

/**
 * phase 647: invariant that every non-local non-node-built-in import in
 * .config/tsup.config.ts, .config/vitest.config.ts, and
 * .config/vitest-setup.ts resolves to a package in package.json
 * (dependencies ∪ devDependencies).
 *
 * Extends phase 646 (eslint.config.js → deps) to cover the remaining
 * config TS files. Same coupling: config literal imports + package.json
 * deps. Drift breaks at config load:
 * - add new package import but forget deps → install succeeds, `pnpm
 *   build` / `pnpm test:run` throws Cannot find module
 * - remove deps but config keeps import → same throw
 *
 * Skips:
 * - `./`, `../` (local imports)
 * - `node:*` (built-in modules; not in package.json)
 * - vitest-global-setup.ts (only node built-ins, no external deps)
 * - dependency-cruiser.cjs (uses module.exports, no imports)
 *
 * Pairs with phase 646 (eslint.config imports → deps), phase 511
 * (no-unused-node-modules — reverse direction).
 */
describe('config files imports ⊆ package deps invariant (phase 647)', () => {
  it('every non-local non-builtin import resolves to package.json dep', () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const CONFIG_FILES = [
      '.config/tsup.config.ts',
      '.config/vitest.config.ts',
      '.config/vitest-setup.ts',
    ];

    const pkg = JSON.parse(
      fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf-8'),
    ) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const allDeps = new Set([
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ]);

    const toPkgRoot = (spec: string): string => {
      if (spec.startsWith('@')) {
        const parts = spec.split('/');
        return parts.slice(0, 2).join('/');
      }
      return spec.split('/')[0];
    };

    const importRe = /^import\s+[\s\S]*?from\s+['"]([^'"]+)['"]/gm;
    const offenders: string[] = [];
    for (const f of CONFIG_FILES) {
      const text = fs.readFileSync(path.join(repoRoot, f), 'utf-8');
      let m: RegExpExecArray | null;
      while ((m = importRe.exec(text)) !== null) {
        const spec = m[1];
        if (spec.startsWith('.')) continue; // local
        if (spec.startsWith('node:')) continue; // built-in
        const pkgRoot = toPkgRoot(spec);
        if (!allDeps.has(pkgRoot)) {
          offenders.push(`${f}: ${spec} (root=${pkgRoot}) not in deps`);
        }
      }
      importRe.lastIndex = 0;
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('package-tsup-entry-pairing-invariant', () => {

/**
 * phase 613: invariant that every package.json entry path (main / module /
 * bin / exports['.']) maps to a tsup config entry with the matching format
 * (esm → .js, cjs → .cjs).
 *
 * Rationale (ML#9 explicit coupling): package.json entry paths and tsup
 * build entries are an inescapable coupling. Drift breaks invisibly until
 * publish:
 * - tsup drops `cli` entry but package.json keeps `bin.chestnut` →
 *   `npm install` succeeds, `chestnut` command fails with ENOENT.
 * - tsup renames entry → package.json stays on old name → same break.
 *
 * Extends phase 612 (path shape) with build-config target verification.
 *
 * Skips `types` field (auto-generated by `dts: true` from the library
 * build entry).
 */
type TsupEntry = { entry: Record<string, string>; format: string[] };

describe('package.json ↔ tsup entry pairing invariant (phase 613)', () => {
  it('every package entry path maps to a tsup entry with matching format', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const pkgPath = path.join(repoRoot, 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
      main?: string;
      module?: string;
      bin?: Record<string, string>;
      exports?: Record<string, Record<string, string>>;
    };

    const tsupCfgPath = path.join(repoRoot, '.config/tsup.config.ts');
    const mod = (await import(tsupCfgPath)) as { default?: unknown };
    const raw = mod.default;
    // tsup defineConfig returns an array (or a function) — here it's an array.
    const tsupEntries: TsupEntry[] = Array.isArray(raw) ? (raw as TsupEntry[]) : [];
    expect(tsupEntries.length).toBeGreaterThan(0);

    // Build a set of (entryName, format) tuples produced by tsup.
    const produced = new Set<string>();
    for (const seg of tsupEntries) {
      for (const name of Object.keys(seg.entry ?? {})) {
        for (const fmt of seg.format ?? []) produced.add(`${name}:${fmt}`);
      }
    }

    const pkgPaths: Array<{ label: string; value: string | undefined }> = [
      { label: 'main', value: pkg.main },
      { label: 'module', value: pkg.module },
      { label: 'bin.chestnut', value: pkg.bin?.chestnut },
      { label: 'exports["."].import', value: pkg.exports?.['.']?.import },
      { label: 'exports["."].require', value: pkg.exports?.['.']?.require },
    ];

    const offenders: string[] = [];
    for (const { label, value } of pkgPaths) {
      if (typeof value !== 'string') {
        offenders.push(`${label}: not a string`);
        continue;
      }
      const m = value.match(/^\.\/dist\/([^/]+)\.(js|cjs)$/);
      if (!m) {
        offenders.push(`${label}=${value}: doesn't match ./dist/<name>.{js|cjs}`);
        continue;
      }
      const [, name, ext] = m;
      const fmt = ext === 'cjs' ? 'cjs' : 'esm';
      if (!produced.has(`${name}:${fmt}`)) {
        offenders.push(`${label}=${value}: tsup has no (${name}, ${fmt}) entry`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('tsconfig-build-behavior-invariant', () => {

/**
 * phase 620: invariant that tsconfig.json compilerOptions build-behavior
 * flags are at baseline:
 * - esModuleInterop === true        — ESM/CJS interop
 * - skipLibCheck === true           — skip .d.ts in node_modules
 * - forceConsistentCasingInFileNames === true — defend macOS case-insensitive
 * - resolveJsonModule === true      — allow JSON import
 * - declaration === true            — emit .d.ts
 * - declarationMap === true         — emit .d.ts.map (IDE jump-to-source)
 * - sourceMap === true              — emit .js.map (debug stack)
 *
 * Plus: types === ['node'] — limit ambient global types to @types/node only,
 * preventing ambient pollution from other @types/* packages.
 *
 * Pairs with phase 608 (strict-family), phase 618 (scope), phase 619
 * (module mode). Closes the remaining compilerOptions coverage gap.
 */
describe('tsconfig.json build behavior baseline invariant (phase 620)', () => {
  it('7 build behavior flags + types match baseline', () => {
    const cfgPath = path.resolve(__dirname, '../../../tsconfig.json');
    const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8')) as {
      compilerOptions?: Record<string, unknown>;
    };
    const co = cfg.compilerOptions ?? {};
    const REQUIRED_TRUE = [
      'esModuleInterop',
      'skipLibCheck',
      'forceConsistentCasingInFileNames',
      'resolveJsonModule',
      'declaration',
      'declarationMap',
      'sourceMap',
    ];
    const offenders: string[] = [];
    for (const flag of REQUIRED_TRUE) {
      if (co[flag] !== true) offenders.push(`${flag}=${String(co[flag])}`);
    }
    expect(offenders).toEqual([]);
    expect(co.types).toEqual(['node']);
  });
});
});

describe('tsconfig-module-mode-invariant', () => {

/**
 * phase 619: invariant that tsconfig.json compilerOptions module-mode
 * baseline is:
 * - target === 'ES2022'
 * - module === 'NodeNext'
 * - moduleResolution === 'NodeNext'
 * - lib === ['ES2022']
 *
 * Rationale (ML#3 single-source module mode): tsc module mode + package.json
 * type=module + tsup target jointly decide .js parse behavior.
 * - target drift down (ES2018) → ES2022 syntax (?? =, structuredClone) fails
 *   to type-check or runtime-error
 * - module/moduleResolution drift off NodeNext → import path resolution
 *   changes (e.g. missing .js suffix in ESM)
 * - lib drift → missing ES2022 globals (Array.prototype.at, structuredClone)
 *
 * Pairs with phase 608 (strict-family), phase 618 (scope baseline), phase
 * 612 (package.json type=module), phase 614 (tsup target uniformity).
 */
describe('tsconfig.json module mode baseline invariant (phase 619)', () => {
  it('target/module/moduleResolution/lib match baseline', () => {
    const cfgPath = path.resolve(__dirname, '../../../tsconfig.json');
    const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8')) as {
      compilerOptions?: {
        target?: unknown;
        module?: unknown;
        moduleResolution?: unknown;
        lib?: unknown;
      };
    };
    const co = cfg.compilerOptions ?? {};
    expect(co.target).toBe('ES2022');
    expect(co.module).toBe('NodeNext');
    expect(co.moduleResolution).toBe('NodeNext');
    expect(co.lib).toEqual(['ES2022']);
  });
});
});

describe('tsconfig-scope-baseline-invariant', () => {

/**
 * phase 618: invariant that tsconfig.json source/output scope is:
 * - include === ['src/**\/*']
 * - exclude === ['node_modules', 'dist', 'tests']
 * - compilerOptions.rootDir === './src'
 * - compilerOptions.outDir === './dist'
 *
 * Rationale (ML#3 single-source scope):
 * - include drift to include tests → tsc reports errors on test fixtures
 *   that intentionally violate strict-family rules
 * - exclude drift drops 'tests' → same surface
 * - rootDir drift → dist structure changes (relative path origin moves) →
 *   published package paths break
 * - outDir drift → tsc and tsup write to different dirs → CI / publish
 *   races
 *
 * Pairs with phase 608 (strict-family flags), phase 615 (depcruise
 * options), phase 612/613 (package.json / tsup).
 */
describe('tsconfig.json scope baseline invariant (phase 618)', () => {
  it('include/exclude/rootDir/outDir match baseline', () => {
    const cfgPath = path.resolve(__dirname, '../../../tsconfig.json');
    const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8')) as {
      include?: unknown;
      exclude?: unknown;
      compilerOptions?: { rootDir?: unknown; outDir?: unknown };
    };
    expect(cfg.include).toEqual(['src/**/*']);
    expect(cfg.exclude).toEqual(['node_modules', 'dist', 'tests']);
    expect(cfg.compilerOptions?.rootDir).toBe('./src');
    expect(cfg.compilerOptions?.outDir).toBe('./dist');
  });
});
});

describe('tsconfig-strict-options-invariant', () => {

/**
 * phase 608: invariant that tsconfig.json compilerOptions has the
 * type-safety strict-family flags all set to true.
 *
 * Rationale: type safety is the baseline of chestnut's coding standards.
 * The strict-family flags are the core constraints — any one set to false
 * lets tsc miss problems the flag was supposed to catch (implicit any,
 * dead code, fall-through switch, unused params, etc.).
 *
 * REQUIRED_FLAGS (all === true):
 * - strict
 * - noUnusedLocals
 * - noUnusedParameters
 * - noImplicitReturns
 * - noFallthroughCasesInSwitch
 * - verbatimModuleSyntax
 */
describe('tsconfig.json strict-family invariant (phase 608)', () => {
  it('compilerOptions has 6 strict-family flags set to true', () => {
    const cfgPath = path.resolve(__dirname, '../../../tsconfig.json');
    const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8')) as {
      compilerOptions?: Record<string, unknown>;
    };
    const co = cfg.compilerOptions ?? {};
    const REQUIRED = [
      'strict',
      'noUnusedLocals',
      'noUnusedParameters',
      'noImplicitReturns',
      'noFallthroughCasesInSwitch',
      'verbatimModuleSyntax',
    ];
    const offenders: string[] = [];
    for (const flag of REQUIRED) {
      if (co[flag] !== true) offenders.push(`${flag}=${String(co[flag])}`);
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('tsup-cli-banner-sourcemap-clean-invariant', () => {

/**
 * phase 629: invariant that tsup config:
 * - every segment has `sourcemap: true`
 * - the CLI-producing segment (entry contains key 'cli') has
 *   `banner.js === '#!/usr/bin/env node'`
 * - exactly one segment has `clean: true`
 *
 * Rationale:
 * - sourcemap on every seg → debug stack traces resolve to TS source
 *   uniformly. One seg lacking sourcemap → dist line numbers in that
 *   bundle's stack traces, harder to diagnose.
 * - CLI banner shebang → npm install -g + invoke `chestnut` requires
 *   shebang for the OS to dispatch to node. Missing shebang → bin file
 *   exists but doesn't execute.
 * - exactly-one clean → multiple `clean: true` segs race; later segs
 *   wipe earlier output, build emits empty dist.
 *
 * Pairs with phase 614 (tsup entry src + target), phase 613 (tsup ↔
 * package pairing), phase 612 (package entry points).
 */
type TsupSeg = {
  entry: Record<string, string>;
  sourcemap?: boolean;
  clean?: boolean;
  banner?: { js?: string };
};

describe('tsup CLI banner + sourcemap + clean invariant (phase 629)', () => {
  it('every seg sourcemap=true + CLI seg has shebang banner + exactly 1 clean', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const cfgPath = path.join(repoRoot, '.config/tsup.config.ts');
    const mod = (await import(cfgPath)) as { default?: unknown };
    const raw = mod.default;
    const segs: TsupSeg[] = Array.isArray(raw) ? (raw as TsupSeg[]) : [];
    expect(segs.length).toBeGreaterThan(0);

    const sourcemapOffenders: string[] = [];
    let cleanCount = 0;
    let cliSegFound = false;
    let cliBannerOk = false;
    for (let i = 0; i < segs.length; i++) {
      const seg = segs[i];
      if (seg.sourcemap !== true) {
        sourcemapOffenders.push(`seg[${i}]: sourcemap=${String(seg.sourcemap)}`);
      }
      if (seg.clean === true) cleanCount += 1;
      if (seg.entry && 'cli' in seg.entry) {
        cliSegFound = true;
        cliBannerOk = seg.banner?.js === '#!/usr/bin/env node';
      }
    }
    expect(sourcemapOffenders).toEqual([]);
    expect(cleanCount).toBe(1);
    expect(cliSegFound).toBe(true);
    expect(cliBannerOk).toBe(true);
  });
});
});

describe('tsup-entry-src-and-target-invariant', () => {

/**
 * phase 614: invariant that every tsup config entry's src path exists on
 * disk AND every tsup build segment targets the same `node18` runtime.
 *
 * Rationale (ML#9 explicit coupling): tsup entry strings are file path
 * references — drift breaks invisibly:
 * - rename / move src file but forget to update tsup entry → tsup build
 *   fails with cryptic resolve error; CI may catch but local dev burns
 *   cycles before seeing it.
 * - inconsistent target across segments → one bundle uses ES2022 syntax,
 *   another uses ES2018; runtime polyfill behavior diverges, node-version
 *   compatibility unpredictable.
 *
 * Extends phase 613 (package.json ↔ tsup entry pairing) to verify the
 * src side of tsup config + cross-segment target uniformity.
 */
type TsupSeg = { entry: Record<string, string>; target?: string };

describe('tsup entry src + target uniformity invariant (phase 614)', () => {
  it('every tsup entry src exists + all segs target node18', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const tsupCfgPath = path.join(repoRoot, '.config/tsup.config.ts');
    const mod = (await import(tsupCfgPath)) as { default?: unknown };
    const raw = mod.default;
    const segs: TsupSeg[] = Array.isArray(raw) ? (raw as TsupSeg[]) : [];
    expect(segs.length).toBeGreaterThan(0);

    const REQUIRED_TARGET = 'node18';
    const offenders: string[] = [];
    for (let i = 0; i < segs.length; i++) {
      const seg = segs[i];
      if (seg.target !== REQUIRED_TARGET) {
        offenders.push(`seg[${i}]: target=${String(seg.target)} (expected ${REQUIRED_TARGET})`);
      }
      for (const [name, srcPath] of Object.entries(seg.entry ?? {})) {
        const resolved = path.resolve(repoRoot, srcPath);
        if (!fs.existsSync(resolved)) {
          offenders.push(`seg[${i}].entry[${name}]: src ${srcPath} missing (resolved=${resolved})`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
});

describe('tsup-library-seg-dts-format-invariant', () => {

/**
 * phase 630: invariant that tsup library segment (entry contains 'index')
 * has `dts: true` AND `format` contains both 'esm' and 'cjs'.
 *
 * Rationale (ML#9 explicit coupling): tsup library seg config is the
 * counterpart of package.json types/main/module fields:
 * - package.json types=./dist/index.d.ts ⇒ library seg must have dts:true
 *   (otherwise npm publish ships package without .d.ts; TS consumers lose
 *   types silently)
 * - package.json main=./dist/index.cjs ⇒ library seg must format includes
 *   'cjs' (otherwise the CJS main path points at non-existent file;
 *   require() throws for CJS consumers)
 * - package.json module=./dist/index.js ⇒ library seg must format
 *   includes 'esm' (otherwise ESM import path missing)
 *
 * Extends phase 629 (CLI banner/sourcemap/clean) + phase 613 (package ↔
 * tsup pairing) to the library-seg specific dist artifact shape.
 */
type TsupSeg = {
  entry: Record<string, string>;
  dts?: boolean;
  format?: string[];
};

describe('tsup library seg dts + format invariant (phase 630)', () => {
  it('library seg (entry index) has dts=true + format includes esm+cjs', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const cfgPath = path.join(repoRoot, '.config/tsup.config.ts');
    const mod = (await import(cfgPath)) as { default?: unknown };
    const raw = mod.default;
    const segs: TsupSeg[] = Array.isArray(raw) ? (raw as TsupSeg[]) : [];
    expect(segs.length).toBeGreaterThan(0);

    const librarySeg = segs.find(s => s.entry && 'index' in s.entry);
    expect(librarySeg).toBeDefined();
    const ls = librarySeg as TsupSeg;
    expect(ls.dts).toBe(true);
    const formats = ls.format ?? [];
    expect(formats).toContain('esm');
    expect(formats).toContain('cjs');
  });
});
});

describe('tsup-splitting-minify-invariant', () => {

/**
 * phase 656: invariant that:
 * - library seg (entry contains 'index') has `splitting: false`
 *   → defends against chunking; produces single dist/index.js (package.json
 *     main points at single file)
 * - CLI seg (entry contains 'cli') has `minify: false`
 *   → preserves function names + readable stack traces for debug
 *
 * Rationale:
 * - splitting=true on library seg → output splits into chunks (dist/
 *   index.js + chunks/_*.js); package.json `main: ./dist/index.cjs`
 *   still points at single file but require() at runtime fails to
 *   resolve the chunks → broken package install
 * - minify=true on CLI seg → CLI runtime errors show `a`/`b`/`c`
 *   function names in stack trace; debugging in user terminals becomes
 *   guesswork
 *
 * Pairs with phase 614 (tsup entry src + target), phase 629 (CLI
 * banner/sourcemap/clean), phase 630 (library dts+format).
 */
type TsupSeg = {
  entry: Record<string, string>;
  splitting?: boolean;
  minify?: boolean;
};

describe('tsup splitting + minify invariant (phase 656)', () => {
  it('library seg splitting=false + CLI seg minify=false', async () => {
    const repoRoot = path.resolve(__dirname, '../../..');
    const cfgPath = path.join(repoRoot, '.config/tsup.config.ts');
    const mod = (await import(cfgPath)) as { default?: unknown };
    const raw = mod.default;
    const segs: TsupSeg[] = Array.isArray(raw) ? (raw as TsupSeg[]) : [];
    expect(segs.length).toBeGreaterThan(0);

    const librarySeg = segs.find(s => s.entry && 'index' in s.entry);
    const cliSeg = segs.find(s => s.entry && 'cli' in s.entry);

    expect(librarySeg, 'library seg with entry index missing').toBeDefined();
    expect(cliSeg, 'CLI seg with entry cli missing').toBeDefined();

    expect((librarySeg as TsupSeg).splitting).toBe(false);
    expect((cliSeg as TsupSeg).minify).toBe(false);
  });
});
});

